let art20th =  [
  {
    id: 1,
    author: 'Пабло Пикассо',
    name: 'Дружба',
    year: '1908',
    image: './src/img/art20th/1.jpg',
  },
  {
    id: 2,
    author: 'Николай Рерих',
    name: 'Горная обитель',
    year: '1933',
    image: './src/img/art20th/2.jpg',
  },
  {
    id: 3,
    author: 'Пабло Пикассо',
    name: 'Любительница абсента',
    year: '1901',
    image: './src/img/art20th/3.jpg',
  },
  {
    id: 4,
    author: 'Марианна Верёвкина',
    name: 'Осень, школа',
    year: '1907',
    image: './src/img/art20th/4.jpg',
  },
  {
    id: 5,
    author: 'Марианна Верёвкина',
    name: 'Муравейник',
    year: '1916',
    image: './src/img/art20th/5.jpg',
  },
  {
    id: 6,
    author: 'Марк Шагал',
    name: 'Я и деревня',
    year: '1911',
    image: './src/img/art20th/6.jpg',
  },
  {
    id: 7,
    author: 'Анри Матисс',
    name: 'Семейный портрет',
    year: '1911',
    image: './src/img/art20th/7.jpg',
  },
  {
    id: 8,
    author: 'Казимир Малевич',
    name: 'Черный квадрат',
    year: '1915',
    image: './src/img/art20th/8.jpg',
  },
  {
    id: 9,
    name: 'Сон, вызванный полётом пчелы вокруг граната, за секунду до пробуждения',
    year: '1944',
    image: './src/img/art20th/9.jpg',
  },
  {
    id: 10,
    author: 'Василий Кандинский',
    name: 'Композиция VIII',
    year: '1923',
    image: './src/img/art20th/10.jpg',
  },
  {
    id: 11,
    author: 'Густав Климт',
    name: 'Поцелуй',
    year: '1908',
    image: './src/img/art20th/11.jpg',
  },
  {
    id: 12,
    author: 'Кузьма Петров-Водкин',
    name: 'Купание красного коня',
    year: '1912',
    image: './src/img/art20th/12.jpg',
  },
  {
    id: 13,
    author: 'Пабло Пикассо',
    name: 'Авиньонские девицы',
    year: '1907',
    image: './src/img/art20th/13.jpg',
  },
  {
    id: 14,
    author: 'Густав Климт',
    name: 'Золотая Адель',
    year: '1907',
    image: './src/img/art20th/14.jpg',
  },
  {
    id: 15,
    author: 'Сальвадор Дали',
    name: 'Постоянство памяти',
    year: '1931',
    image: './src/img/art20th/15.jpg',
  },
  {
    id: 16,
    author: 'Марк Шагал',
    name: 'Прогулка',
    year: '1918',
    image: './src/img/art20th/16.jpg',
  },
  {
    id: 17,
    author: 'Анри Матисс',
    name: 'Танец',
    year: '1910',
    image: './src/img/art20th/17.jpg',
  },
  {
    id: 18,
    author: 'Рене Магритт',
    name: 'Сын человеческий',
    year: '1964',
    image: './src/img/art20th/18.jpg',
  },
  {
    id: 19,
    author: 'Пабло Пикассо',
    name: 'Герника',
    year: '1937',
    image: './src/img/art20th/19.jpg',
  },
  {
    id: 20,
    author: 'Пабло Пикассо',
    name: 'Девочка на шаре',
    year: '1905',
    image: './src/img/art20th/20.jpg',
  },
  {
    id: 21,
    author: 'Зинаида Серебрякова',
    name: 'За завтраком',
    year: '1914',
    image: './src/img/art20th/21.jpg',
  },
  {
    id: 22,
    author: 'Валентин Серов',
    name: 'Портрет княгини З. Н. Юсуповой',
    year: '1902',
    image: './src/img/art20th/22.jpg',
  },
  {
    id: 23,
    author: 'Борис Кустодиев',
    name: 'Купчиха за чаем',
    year: '1918',
    image: './src/img/art20th/23.jpg',
  },
  {
    id: 24,
    author: 'Зинаида Серебрякова',
    name: 'Балетная уборная',
    year: '1924',
    image: './src/img/art20th/24.jpg',
  },
  {
    id: 25,
    author: 'Юрий Пименов',
    name: 'Лирическое новоселье', 
    year: '1965',
    image: './src/img/art20th/25.jpg',
  },
  {
    id: 26,
    author: 'Пит Мондриан',
    name: 'Композиция с красным, синим и жёлтым',
    year: '1930',
    image: './src/img/art20th/26.jpg',
  },
  {
    id: 27,
    author: 'Пит Мондриан',
    name: 'Композиция с цветными плоскостями и серыми линиями',
    year: '1918',
    image: './src/img/art20th/27.jpg',
  },
  {
    id: 28,
    author: 'Анри Руссо',
    name: 'Муза, вдохновляющая поэта',
    year: '1909',
    image: './src/img/art20th/28.jpg',
  },
  {
    id: 29,
    author: 'Август Макке',
    name: 'Дама в зеленом жакете',
    year: '1913',
    image: './src/img/art20th/29.jpg',
  },
  {
    id: 30,
    author: 'Андре Дерен',
    name: 'Мост Чаринг-Кросс',
    year: '1906',
    image: './src/img/art20th/30.jpg',
  },
]

export default art20th;