let artstart = [
  {
    id: 1,
    author: 'Вильгельм фон Каульбах',
    name: 'Разрушение Иерусалима',
    year: '1846',
    image: './src/img/art1-19/1.jpg',
  },
  {
    id: 2,
    author: 'Алексей Венецианов',
    name: 'Спящий пастушок',
    year: '1826',
    image: './src/img/art1-19/2.jpg',
  },
  {
    id: 3,
    author: 'Карл Брюллов',
    name: 'Всадница',
    year: '1832',
    image: './src/img/art1-19/3.jpg',
  },
  {
    id: 4,
    author: 'Василий Верещагин',
    name: 'Апофеоз войны',
    year: '1817',
    image: './src/img/art1-19/4.jpg',
  },
  {
    id: 5,
    author: 'Василий Тропинин',
    name: 'Девушка с горшком роз',
    year: '1850',
    image: './src/img/art1-19/5.jpg',
  },
  {
    id: 6,
    author: 'Алексей Венецианов',
    name: 'На пашне. Весна',
    year: '1820',
    image: './src/img/art1-19/6.jpg',
  },
  {
    id: 7,
    author: 'Иван Айвазовский',
    name: 'Девятый вал',
    year: '1850',
    image: './src/img/art1-19/7.jpg',
  },
  {
    id: 8,
    author: 'Эжен Делакруа',
    name: 'Свобода, ведущая народ',
    year: '1830',
    image: './src/img/art1-19/8.jpg',
  },
  {
    id: 9,
    author: 'Карл Брюллов',
    name: 'Итальянский полдень',
    year: '1827',
    image: './src/img/art1-19/9.jpg',
  },
  {
    id: 10,
    author: 'Франциско Гоя',
    name: 'Расстрел повстанцев',
    year: '1808',
    image: './src/img/art1-19/10.jpg',
  },
  {
    id: 11,
    author: 'Поль Деларош',
    name: 'Казнь Джейн Грей',
    year: '1833',
    image: './src/img/art1-19/11.jpg',
  },
  {
    id: 12,
    author: 'Джон Констебл',
    name: 'Вид на собор в Солсбери из епископского сада',
    year: '1823',
    image: './src/img/art1-19/12.jpg',
  },
  {
    id: 13,
    author: 'Василий Тропинин',
    name: 'Кружевница',
    year: '1823',
    image: './src/img/art1-19/13.jpg',
  },
  {
    id: 14,
    author: 'Алексей Венецианов',
    name: 'На жатве. Лето',
    year: '1827',
    image: './src/img/art1-19/14.jpg',
  },
  {
    id: 15,
    author: 'Эжен Делакруа',
    name: 'Автопортрет',
    year: '1837',
    image: './src/img/art1-19/15.jpg',
  },
  {
    id: 16,
    author: 'Карл Брюллов',
    name: 'Последний день Помпеи',
    year: '1833',
    image: './src/img/art1-19/16.jpg',
  },
  {
    id: 17,
    author: 'Эмануэль Лойце',
    name: 'Вашингтон переправляется через Делавэр',
    year: '1851',
    image: './src/img/art1-19/17.jpg',
  },
  {
    id: 18,
    author: 'Жак Луи Давид',
    name: 'Бонапарт на перевале Сен-Бернар',
    year: '1801',
    image: './src/img/art1-19/18.jpg',
  },
  {
    id: 19,
    author: 'Эжен Делакруа',
    name: 'Смерть Сарданапала',
    year: '1827',
    image: './src/img/art1-19/19.jpg',
  },
  {
    id: 20,
    author: 'Каспар Давид Фридрих',
    name: 'Странник над морем тумана',
    year: '1818',
    image: './src/img/art1-19/20.jpg',
  },
  {
    id: 21,
    author: 'Поль Деларош',
    name: 'Полукружия. Фреска (центральная часть)',
    year: '1842',
    image: './src/img/art1-19/21.jpg',
  },
  {
    id: 22,
    author: 'Фридрих Амерлинг',
    name: 'Портрет Рудольфа фон Артхабера с детьми',
    year: '1837',
    image: './src/img/art1-19/22.jpg',
  },
  {
    id: 23,
    author: 'Фридрих Овербек',
    name: 'Италия и Германия',
    year: '1828 ',
    image: './src/img/art1-19/23.jpg',
  },
  {
    id: 24,
    author: 'Теодор Жерико',
    name: 'Плот «Медузы»',
    year: '1819',
    image: './src/img/art1-19/24.jpg',
  },
  {
    id: 25,
    author: 'Карл Брюллов',
    name: 'Всадница',
    year: '1832',
    image: './src/img/art1-19/25.jpg',
  },
  {
    id: 26,
    author: 'Уильям Тёрнер',
    name: 'Голландские лодки в шторм',
    year: '1801',
    image: './src/img/art1-19/26.jpg',
  },
  {
    id: 27,
    author: 'Каспар Давид Фридрих',
    name: 'Три возраста жизни',
    year: '1835',
    image: './src/img/art1-19/27.jpg',
  },
  {
    id: 28,
    author: 'Жак Луи Давид',
    name: 'Коронование императора Наполеона I и императрицы Жозефины',
    year: '1808',
    image: './src/img/art1-19/28.jpg',
  },
  {
    id: 29,
    author: 'Жан Огюст Энгр',
    name: 'Большая одалиска',
    year: '1814',
    image: './src/img/art1-19/29.jpg',
  },
  {
    id: 30,
    author: 'Александр Кабанель',
    name: 'Падший ангел ',
    year: '1847',
    image: './src/img/art1-19/30.jpg',
  },
]

export default artstart;