let artend = [
  {
    id: 1,
    author: 'Павел Федотов',
    name: 'Сватовство майора',
    year: '1852',
    image: './src/img/art2-19/1.jpg',
  },
  {
    id: 2,
    author: 'Эдгар Дега',
    name: 'Голубые танцовщицы',
    year: '1897',
    image: './src/img/art2-19/2.jpg',
  },
  {
    id: 3,
    author: 'Илья Репин',
    name: 'Иван Грозный и сын его Иван',
    year: '1885',
    image: './src/img/art2-19/3.jpg',
  },
  {
    id: 4,
    author: 'Константин Маковский',
    name: 'Портрет графини Софьи',
    year: '1890',
    image: './src/img/art2-19/4.jpg',
  },
  {
    id: 5,
    author: 'Василий Перов',
    name: 'Приезд гувернантки в купеческий дом',
    year: '1866',
    image: './src/img/art2-19/5.jpg',
  },
  {
    id: 6,
    author: 'Пьер Огюст Ренуар',
    name: 'Прогулка в Булонском лесу',
    year: '1873',
    image: './src/img/art2-19/6.jpg',
  },
  {
    id: 7,
    author: 'Василий Поленов',
    name: 'Московский дворик',
    year: '1877',
    image: './src/img/art2-19/7.jpg',
  },
  {
    id: 8,
    author: 'Илья Репин',
    name: 'Проводы новобранца',
    year: '1879',
    image: './src/img/art2-19/8.jpg',
  },
  {
    id: 9,
    author: 'Архип Куинджи',
    name: 'Берёзовая роща',
    year: '1879',
    image: './src/img/art2-19/9.jpg',
  },
  {
    id: 10,
    author: 'Поль Гоген',
    name: 'Откуда мы пришли? Кто мы? Куда мы идём?',
    year: '1898',
    image: './src/img/art2-19/10.jpg',
  },
  {
    id: 11,
    author: 'Константин Маковский',
    name: 'Дети, бегущие от грозы',
    year: '1872',
    image: './src/img/art2-19/11.jpg',
  },
  {
    id: 12,
    author: 'Иван Айвазовский',
    name: 'Волна',
    year: '1889',
    image: './src/img/art2-19/12.jpg',
  },
  {
    id: 13,
    author: 'Аксели Галлен-Каллела',
    name: 'Девушка на ветру',
    year: '1893',
    image: './src/img/art2-19/13.jpg',
  },
  {
    id: 14,
    author: 'Эдгар Дега',
    name: 'Балетный класс',
    year: '1874',
    image: './src/img/art2-19/14.jpg',
  },
  {
    id: 15,
    author: 'Аксели Галлен-Каллела',
    name: 'Первый урок',
    year: '1889',
    image: './src/img/art2-19/15.jpg',
  },
  {
    id: 16,
    author: 'Исаак Левитан',
    name: 'Весна – большая вода',
    year: '1897',
    image: './src/img/art2-19/16.jpg',
  },
  {
    id: 17,
    author: 'Клод Моне',
    name: 'Завтрак на траве',
    year: '1865',
    image: './src/img/art2-19/17.jpg',
  },
  {
    id: 18,
    author: 'Иван Шишкин',
    name: 'Сосновый бор',
    year: '1895',
    image: './src/img/art2-19/18.jpg',
  },
  {
    id: 19,
    author: 'Поль Гоген',
    name: 'Кафе в Арле',
    year: '1888',
    image: './src/img/art2-19/19.jpg',
  },
  {
    id: 20,
    author: 'Клод Моне',
    name: 'Пруд с кувшинками',
    year: '1899',
    image: './src/img/art2-19/20.jpg',
  },
  {
    id: 21,
    author: 'Винсент Ван Гог',
    name: 'Ночное кафе в Арле',
    year: '1888',
    image: './src/img/art2-19/21.jpg',
  },
  {
    id: 22,
    author: 'Аксели Галлен-Каллела',
    name: 'Мальчик и ворона',
    year: '1884',
    image: './src/img/art2-19/22.jpg',
  },
  {
    id: 23,
    author: 'Василий Суриков',
    name: 'Боярыня Морозова',
    year: '1887',
    image: './src/img/art2-19/23.jpg',
  },
  {
    id: 24,
    author: 'Адольф Вильям Бугро',
    name: 'Волна',
    year: '1896',
    image: './src/img/art2-19/24.jpg',
  },
  {
    id: 25,
    author: 'Василий Перов',
    name: 'Охотники на привале',
    year: '1871',
    image: './src/img/art2-19/25.jpg',
  },
  {
    id: 26,
    author: 'Михаил Нестеров',
    name: 'Видение отроку Варфоломею',
    year: '1890',
    image: './src/img/art2-19/26.jpg',
  },
  {
    id: 27,
    author: 'Алексей Саврасов',
    name: 'Грачи прилетели',
    year: '1871',
    image: './src/img/art2-19/27.jpg',
  },
  {
    id: 28,
    author: 'Анри де Тулуз-Лотрек',
    name: 'Угол Мулен де ла Галет',
    year: '1892',
    image: './src/img/art2-19/28.jpg',
  },
  {
    id: 29,
    author: 'Александр Маковский',
    name: 'Надоела',
    year: '1897',
    image: './src/img/art2-19/29.jpg',
  },
  {
    id: 30,
    author: 'Джон Милле',
    name: 'Офелия',
    year: '1852',
    image: './src/img/art2-19/30.jpg',
  },
]

export default artend;