let domestic = [
  {
    id: 1,
    author: 'Рембрандт',
    name: 'Даная',
    year: '1647',
    image: './src/img/domestic/1.jpg',
  },
  {
    id: 2,
    author: 'Василий Перов',
    name: 'Приезд гувернантки в купеческий дом',
    year: '1866',
    image: './src/img/domestic/2.jpg',
  },
  {
    id: 3,
    author: 'Ян Вермеер',
    name: 'Хозяйка и служанка',
    year: '1667',
    image: './src/img/domestic/3.jpg',
  },
  {
    id: 4,
    author: 'Эдуард Мане',
    name: 'Ланч на траве',
    year: '1863',
    image: './src/img/domestic/4.jpg',
  },
  {
    id: 5,
    author: 'Бартоломео Мурильо',
    name: 'Мальчик с собакой',
    year: '1650',
    image: './src/img/domestic/5.jpg',
  },
  {
    id: 6,
    author: 'Ян Вермеер',
    name: 'Молочница',
    year: '1660',
    image: './src/img/domestic/6.jpg',
  },
  {
    id: 7,
    author: 'Эдуард Мане',
    name: 'Женщина с кувшином',
    year: '1858',
    image: './src/img/domestic/7.jpg',
  },
  {
    id: 8,
    author: 'Поль Гоген',
    name: 'Кафе в Арле',
    year: '1888',
    image: './src/img/domestic/8.jpg',
  },
  {
    id: 9,
    author: 'Пабло Пикассо',
    name: 'Любительница абсента',
    year: '1901',
    image: './src/img/domestic/9.jpg',
  },
  {
    id: 10,
    author: 'Питер Брейгель',
    name: 'Избиение младенцев',
    year: '1567',
    image: './src/img/domestic/10.jpg',
  },
  {
    id: 11,
    author: 'Караваджо',
    name: 'Лютнист',
    year: '1596',
    image: './src/img/domestic/11.jpg',
  },
  {
    id: 12,
    author: 'Пьер Огюст Ренуар',
    name: 'Бал в Мулен де ла Галетт',
    year: '1876',
    image: './src/img/domestic/12.jpg',
  },
  {
    id: 13,
    author: 'Винсент ван Гог',
    name: 'Воспоминание о саде в Эттене',
    year: '1888',
    image: './src/img/domestic/13.jpg',
  },
  {
    id: 14,
    author: 'Аксели Галлен-Каллела',
    name: 'Первый урок',
    year: '1889',
    image: './src/img/domestic/14.jpg',
  },
  {
    id: 15,
    author: 'Жан Батист Грёз',
    name: 'Избалованное дитя',
    year: '1765',
    image: './src/img/domestic/15.jpg',
  },
  {
    id: 16,
    author: 'Константин Маковский',
    name: 'Гадание',
    year: '1890',
    image: './src/img/domestic/16.jpg',
  },
  {
    id: 17,
    author: 'Павел Федотов',
    name: 'Завтрак аристократа',
    year: '1849',
    image: './src/img/domestic/17.jpg',
  },
  {
    id: 18,
    author: 'Татьяна Яблонская',
    name: 'Утро',
    year: '1954',
    image: './src/img/domestic/18.jpg',
  },
  {
    id: 19,
    author: 'Илья Репин',
    name: 'Не ждали',
    year: '1888',
    image: './src/img/domestic/19.jpg',
  },
  {
    id: 20,
    author: 'Алексей Венецианов',
    name: 'На жатве. Лето',
    year: '1827',
    image: './src/img/domestic/20.jpg',
  },
  {
    id: 21,
    author: 'Жан Фрагонар',
    name: 'Качели',
    year: '1767',
    image: './src/img/domestic/21.jpg',
  },
  {
    id: 22,
    author: 'Ян Стен',
    name: 'Семейный концерт',
    year: '1666',
    image: './src/img/domestic/22.jpg',
  },
  {
    id: 23,
    author: 'Томас Гейнсборо',
    name: 'Жатва. Возвращение с поля',
    year: '1767',
    image: './src/img/domestic/23.jpg',
  },
  {
    id: 24,
    author: 'Франсиско Гойя',
    name: 'Продажа керамической посуды',
    year: '1779',
    image: './src/img/domestic/24.jpg',
  },
  {
    id: 25,
    author: 'Пабло Пикассо',
    name: 'Девочка на шаре',
    year: '1905',
    image: './src/img/domestic/25.jpg',
  },
  {
    id: 26,
    author: 'Илья Репин',
    name: 'Демонстрация 17 октября 1905 года',
    year: '1907',
    image: './src/img/domestic/26.jpg',
  },
  {
    id: 27,
    author: 'Пьер Огюст Ренуар',
    name: 'Завтрак гребцов',
    year: '1881',
    image: './src/img/domestic/27.jpg',
  },
  {
    id: 28,
    author: 'Клод Моне',
    name: 'Завтрак на траве',
    year: '1865',
    image: './src/img/domestic/28.jpg',
  },
  {
    id: 29,
    author: 'Поединок Демпси и Фирпо',
    name: 'Джордж Беллоуз',
    year: '1924',
    image: './src/img/domestic/28.jpg',
  },
  {
    id: 30,
    author: 'Гюстав Курбе',
    name: 'Бедная крестьянка зимой',
    year: '1866',
    image: './src/img/domestic/30.jpg',
  },
]

export default domestic;
