let historical = [
  {
    id: 1,
    author: 'Илья Репин',
    name: 'Иван Грозный и сын его Иван',
    year: '1885',
    image: './src/img/historical/1.jpg',
  },
  {
    id: 2,
    author: 'Василий Суриков',
    name: 'Покорение Сибири Ермаком Тимофеевичем',
    year: '1895',
    image: './src/img/historical/2.jpg',
  },
  {
    id: 3,
    author: 'Рембрандт',
    name: 'Ночной дозор',
    year: '1642',
    image: './src/img/historical/3.jpg',
  },
  {
    id: 4,
    author: 'Василий Суриков',
    name: 'Переход Суворова через Альпы',
    year: '1899',
    image: './src/img/historical/4.jpg',
  },
  {
    id: 5,
    author: 'Карл Брюллов',
    name: 'Последний день Помпеи',
    year: '1833',
    image: './src/img/historical/5.jpg',
  },
  {
    id: 6,
    author: 'Эжен Делакруа',
    name: 'Свобода, ведущая народ',
    year: '1830',
    image: './src/img/historical/6.jpg',
  },
  {
    id: 7,
    author: 'Константин Маковский',
    name: 'Перемещение ковра Мухаммеда из Мекки в Каир',
    year: '1875',
    image: './src/img/historical/7.jpg',
  },
  {
    id: 8,
    author: 'Илья Репин',
    name: 'Запорожцы',
    year: '1891',
    image: './src/img/historical/9.jpg',
  },
  {
    id: 9,
    author: 'Константин Маковский',
    name: 'Боярский свадебный пир',
    year: '1883',
    image: './src/img/historical/8.jpg',
  },
  {
    id: 10,
    author: 'Гюстав Курбе',
    name: 'Мастерская художника',
    year: '1855',
    image: './src/img/historical/10.jpg',
  },
  {
    id: 11,
    author: 'Виктор Васнецов',
    name: 'Царь Иван Васильевич Грозный',
    year: '1896',
    image: './src/img/historical/11.jpg',
  },
  {
    id: 12,
    author: 'Франциско Гоя',
    name: 'Расстрел повстанцев',
    year: '1808',
    image: './src/img/historical/12.jpg',
  },
  {
    id: 13,
    author: 'Поль Деларош',
    name: 'Казнь Джейн Грей',
    year: '1833',
    image: './src/img/historical/13.jpg',
  },
  {
    id: 14,
    author: 'Веласкес',
    name: 'Сдача Бреды',
    year: '1635',
    image: './src/img/historical/14.jpg',
  },
  {
    id: 15,
    author: 'Эмануэль Лойце',
    name: 'Вашингтон переправляется через Делавэр',
    year: '1851',
    image: './src/img/historical/15.jpg',
  },
  {
    id: 16,
    author: 'Михаил Песков',
    name: 'Воззвание Минина к нижегородцам в 1611 году',
    year: '1861',
    image: './src/img/historical/16.jpg',
  },
  {
    id: 17,
    author: 'Фердинанда Лике',
    name: 'Набег викингов',
    year: '1906',
    image: './src/img/historical/17.jpg',
  },
  {
    id: 18,
    author: 'Вячеслав Шварца',
    name: 'Сцена из домашней жизни русских царей',
    year: '1865',
    image: './src/img/historical/18.jpg',
  },
  {
    id: 19,
    author: 'Жак-Луи Давид',
    name: 'Смерть Сократа',
    year: '1787',
    image: './src/img/historical/19.jpg',
  },
  {
    id: 20,
    author: 'Илья Репин',
    name: 'Царевна Софья',
    year: '1879',
    image: './src/img/historical/20.jpg',
  },
  {
    id: 21,
    author: 'Жак Луи Давид',
    name: 'Клятва в зале для игры в мяч',
    year: '1794',
    image: './src/img/historical/21.jpg',
  },
  {
    id: 22,
    author: 'Жак Луи Давид',
    name: 'Смерть Марата',
    year: '1793',
    image: './src/img/historical/22.jpg',
  },
  {
    id: 23,
    author: 'Жак Луи Давид',
    name: 'Бонапарт на перевале Сен-Бернар',
    year: '1801',
    image: './src/img/historical/23.jpg',
  },
  {
    id: 24,
    author: 'Франсиско Гойя',
    name: '3 мая 1808 года',
    year: '1814',
    image: './src/img/historical/24.jpg',
  },
  {
    id: 25,
    author: 'Вячеслав Шварц',
    name: 'Иоанн Грозный у тела убитого им сына',
    year: '1864',
    image: './src/img/historical/25.jpg',
  },
  {
    id: 26,
    author: 'Эжен Делакруа',
    name: 'Смерть Сарданапала',
    year: '1827',
    image: './src/img/historical/26.jpg',
  },
  {
    id: 27,
    author: 'Антон Лосенко',
    name: 'Владимир и Рогнеда',
    year: '1770',
    image: './src/img/historical/27.jpg',
  },
  {
    id: 28,
    author: 'Ян Матейко',
    name: 'Рейтан. Упадок Польши',
    year: '1866',
    image: './src/img/historical/28.jpg',
  },
  {
    id: 29,
    author: 'Василий Суриков',
    name: 'Степан Разин',
    year: '1906',
    image: './src/img/historical/29.jpg',
  },
  {
    id: 30,
    author: 'Василий Перов',
    name: 'Плач Ярославны',
    year: '1881',
    image: './src/img/historical/30.jpg',
  },
]

export default historical;