let impressionism = [
  {
    id: 1,
    author: 'Эдгар Дега',
    name: 'Голубые танцовщицы',
    year: '1897',
    image: './src/img/impressionism/1.jpg',
  },
  {
    id: 2,
    author: 'Пьер Огюст Ренуар',
    name: 'Большие купальщицы',
    year: '1887',
    image: './src/img/impressionism/2.jpg',
  },
  {
    id: 3,
    author: 'Эдуард Мане',
    name: 'Ланч на траве',
    year: '1863',
    image: './src/img/impressionism/3.jpg',
  },
  {
    id: 4,
    author: 'Станислав Юлианович Жуковский',
    name: 'Былое. Комната старого дома ',
    year: '1912',
    image: './src/img/impressionism/4.jpg',
  },
  {
    id: 5,
    author: 'Абрам Архипов',
    name: 'Баба в красном',
    year: '1910',
    image: './src/img/impressionism/5.jpg',
  },
  {
    id: 6,
    author: 'Клод Моне',
    name: 'Пруд с кувшинками',
    year: '1899',
    image: './src/img/impressionism/6.jpg',
  },
  {
    id: 7,
    author: 'Николай Мещерин',
    name: 'РЖАНЫЕ ПОЛЯ. ВИД ОТ ВОРОТ УСАДЬБЫ ДУГИНО В СТОРОНУ СЕЛА КОЛЫЧЕВО',
    year: '1906',
    image: './src/img/impressionism/7.jpg',
  },
  {
    id: 8,
    author: 'Валентин Александрович Серов',
    name: 'Открытое окно. Сирень',
    year: '1886',
    image: './src/img/impressionism/8.jpg',
  },
  {
    id: 9,
    author: 'Алексей Саврасов',
    name: 'Перед грозой',
    year: '1890',
    image: './src/img/impressionism/9.jpg',
  },
  {
    id: 10,
    author: 'Винсент Ван Гог.',
    name: ' Звёздная ночь',
    year: '1889',
    image: './src/img/impressionism/10.jpg',
  },
  {
    id: 11,
    author: 'Жорж Сёра',
    name: 'Воскресный день на острове Гранд-Жатт',
    year: '1884',
    image: './src/img/impressionism/11.jpg',
  },
  {
    id: 12,
    author: 'Джон Сингер Сарджент',
    name: 'Сладкое безделье',
    year: '1907',
    image: './src/img/impressionism/12.jpg',
  },
  {
    id: 13,
    author: 'Уолтер Сикерт',
    name: 'Крошка Дот Хетерингтон в Старом Бедфорде',
    year: '1889',
    image: './src/img/impressionism/13.jpg',
  },
  {
    id: 14,
    author: 'Камиль Писсарро',
    name: 'Бульвар Монмартр в Париже',
    year: '1897',
    image: './src/img/impressionism/14.jpg',
  },
  {
    id: 15,
    author: 'Максимильен Люс',
    name: 'Монмартр, улица Кортот, вид из Сен-Дени',
    year: '1900',
    image: './src/img/impressionism/15.jpg',
  },
  {
    id: 16,
    author: 'Анри де Тулуз-Лотрек',
    name: 'Марселла Лендер, танцующая болеро в кабаре',
    year: '1895',
    image: './src/img/impressionism/16.jpg',
  },
  {
    id: 17,
    author: 'Берта Моризо',
    name: 'Летний день',
    year: '1879',
    image: './src/img/impressionism/17.jpg',
  },
  {
    id: 18,
    author: 'Анри Руссо',
    name: 'Заклинательница змей',
    year: '1907',
    image: './src/img/impressionism/18.jpg',
  },
  {
    id: 19,
    author: 'Альфред Сислей',
    name: 'Мост Море́ летом',
    year: '1888',
    image: './src/img/impressionism/19.jpg',
  },
  {
    id: 20,
    author: 'Поль Сезанн',
    name: 'Натюрморт с драпировкой',
    year: '1895',
    image: './src/img/impressionism/20.jpg',
  },
  {
    id: 21,
    author: 'Жан Фредерик Базиль',
    name: 'В кругу семьи',
    year: '1867',
    image: './src/img/impressionism/21.jpg',
  },
  {
    id: 22,
    author: 'Матисс, Анри',
    name: 'Танец',
    year: '1910',
    image: './src/img/impressionism/22.jpg',
  },
  {
    id: 23,
    author: 'Поль Синьяк',
    name: 'Сосна Берто. Сен-Тропе',
    year: '1909',
    image: './src/img/impressionism/23.jpg',
  },
  {
    id: 24,
    author: 'Константин Коровин',
    name: 'В лодке',
    year: '1888',
    image: './src/img/impressionism/24.jpg',
  },
  {
    id: 25,
    author: 'Поль Гоген',
    name: 'Кафе в Арле',
    year: '1888',
    image: './src/img/impressionism/25.jpg',
  },
  {
    id: 26,
    author: 'Исаак Левитан',
    name: 'Мостик. Саввинская слобода',
    year: '1884',
    image: './src/img/impressionism/26.jpg',
  },
  {
    id: 27,
    author: 'Поль Серюзье',
    name: 'Ливень',
    year: '1893',
    image: './src/img/impressionism/27.jpg',
  },
  {
    id: 28,
    author: 'Пьер Боннар',
    name: 'Виноград',
    year: '1923',
    image: './src/img/impressionism/28.jpg',
  },
  {
    id: 29,
    author: 'Морис Дени',
    name: 'Завтрак',
    year: '1901',
    image: './src/img/impressionism/29.jpg',
  },
  {
    id: 30,
    author: 'Гюстав Кайботт',
    name: 'Крыши под снегом',
    year: '1878',
    image: './src/img/impressionism/30.jpg',
  },
]

export default impressionism;