let impressionism = [
  {
    id: 1,
    author: 'Эдгар Дега',
    name: 'Голубые танцовщицы',
    year: '1897',
    image: './src/img/impressionism/1.jpg',
  },
  {
    id: 2,
    author: 'Пьер Огюст Ренуар',
    name: 'Большие купальщицы',
    year: '1887',
    image: './src/img/impressionism/2.jpg',
  },
  {
    id: 3,
    author: 'Эдуард Мане',
    name: 'Ланч на траве',
    year: '1863',
    image: './src/img/impressionism/3.jpg',
  },
  {
    id: 4,
    author: 'Пьер Огюст Ренуар',
    name: 'Две девушки',
    year: '1892',
    image: './src/img/impressionism/4.jpg',
  },
  {
    id: 5,
    author: 'Клод Моне',
    name: 'Мост Ватерлоо, туман',
    year: '1903',
    image: './src/img/impressionism/5.jpg',
  },
  {
    id: 6,
    author: 'Клод Моне',
    name: 'Пруд с кувшинками',
    year: '1899',
    image: './src/img/impressionism/6.jpg',
  },
  {
    id: 7,
    author: 'Клод Моне',
    name: 'Впечатление. Восходящее солнце',
    year: '1882',
    image: './src/img/impressionism/7.jpg',
  },
  {
    id: 8,
    author: 'Эдуард Мане',
    name: 'Бар в «Фоли-Бержер»',
    year: '1882',
    image: './src/img/impressionism/8.jpg',
  },
  {
    id: 9,
    author: 'Пьер Огюст Ренуар',
    name: 'Портрет Жанны Самари',
    year: '1877',
    image: './src/img/impressionism/9.jpg',
  },
  {
    id: 10,
    author: 'Пьер Огюст Ренуар',
    name: 'Завтрак гребцов',
    year: '1881',
    image: './src/img/impressionism/10.jpg',
  },
  {
    id: 11,
    author: 'Пьер Огюст Ренуар',
    name: 'Мост в Шату',
    year: '1875',
    image: './src/img/impressionism/11.jpg',
  },
  {
    id: 12,
    author: 'Джон Сингер Сарджент',
    name: 'Сладкое безделье',
    year: '1907',
    image: './src/img/impressionism/12.jpg',
  },
  {
    id: 13,
    author: 'Уолтер Сикерт',
    name: 'Крошка Дот Хетерингтон в Старом Бедфорде',
    year: '1889',
    image: './src/img/impressionism/13.jpg',
  },
  {
    id: 14,
    author: 'Камиль Писсарро',
    name: 'Бульвар Монмартр в Париже',
    year: '1897',
    image: './src/img/impressionism/14.jpg',
  },
  {
    id: 15,
    author: 'Камиль Писсарро',
    name: 'Церковь Сен-Жак в Дьепе',
    year: '1901',
    image: './src/img/impressionism/15.jpg',
  },
  {
    id: 16,
    author: 'Камиль Писсарро',
    name: 'Каштаны в Лувесьене,',
    year: '1870',
    image: './src/img/impressionism/16.jpg',
  },
  {
    id: 17,
    author: 'Берта Моризо',
    name: 'Летний день',
    year: '1879',
    image: './src/img/impressionism/17.jpg',
  },
  {
    id: 18,
    author: 'Берта Моризо',
    name: 'В столовой',
    year: '1886',
    image: './src/img/impressionism/18.jpg',
  },
  {
    id: 19,
    author: 'Альфред Сислей',
    name: 'Мост Море́ летом',
    year: '1888',
    image: './src/img/impressionism/19.jpg',
  },
  {
    id: 20,
    author: 'Альфред Сислей',
    name: 'Баржи в Бийянкуре',
    year: '1877',
    image: './src/img/impressionism/20.jpg',
  },
  {
    id: 21,
    author: 'Жан Фредерик Базиль',
    name: 'В кругу семьи',
    year: '1867',
    image: './src/img/impressionism/21.jpg',
  },
  {
    id: 22,
    author: 'Жан Фредерик Базиль',
    name: 'Вид на деревню',
    year: '1868',
    image: './src/img/impressionism/22.jpg',
  },
  {
    id: 23,
    author: 'Жан Фредерик Базиль',
    name: 'Летняя сцена (Купальщики) ',
    year: '1869',
    image: './src/img/impressionism/23.jpg',
  },
  {
    id: 24,
    author: 'Константин Коровин',
    name: 'В лодке',
    year: '1888',
    image: './src/img/impressionism/24.jpg',
  },
  {
    id: 25,
    author: 'Константин Коровин',
    name: '1914',
    year: 'Гурзуф',
    image: './src/img/impressionism/25.jpg',
  },
  {
    id: 26,
    author: 'Исаак Левитан',
    name: 'Мостик. Саввинская слобода',
    year: '1884',
    image: './src/img/impressionism/26.jpg',
  },
  {
    id: 27,
    author: 'Исаак Левитан',
    name: 'Лилии. Ненюфары',
    year: '1895',
    image: './src/img/impressionism/27.jpg',
  },
  {
    id: 28,
    author: 'Исаак Левитан',
    name: 'После дождя. Плёс',
    year: '1889',
    image: './src/img/impressionism/28.jpg',
  },
  {
    id: 29,
    author: 'Пьер Огюст Ренуар',
    name: 'Зонтики',
    year: '1886',
    image: './src/img/impressionism/29.jpg',
  },
  {
    id: 30,
    author: 'Гюстав Кайботт',
    name: 'Крыши под снегом',
    year: '1878',
    image: './src/img/impressionism/30.jpg',
  },
]

export default impressionism;