let imageslandscapes = [
  {
    id: 1,
    author: 'Василий Поленов',
    name: 'Московский дворик',
    year: '1877',
    image: './src/img/landscapes/1.jpg',
  },
  {
    id: 2,
    author: 'Фёдор Васильев',
    name: 'Мокрый луг',
    year: '1872',
    image: './src/img/landscapes/2.jpg',
  },
  {
    id: 3,
    author: 'Клод Лоррен',
    name: 'Отплытие святой Урсулы',
    year: '1614',
    image: './src/img/landscapes/3.jpg',
  },
  {
    id: 4,
    author: 'Архип Куинджи',
    name: 'Берёзовая роща',
    year: '1879',
    image: './src/img/landscapes/4.jpg',
  },
  {
    id: 5,
    author: 'Эль Греко',
    name: 'Вид Толедо',
    year: '1600',
    image: './src/img/landscapes/5.jpg',
  },
  {
    id: 6,
    author: 'Джорджоне',
    name: 'Буря',
    year: '1508',
    image: './src/img/landscapes/6.jpg',
  },
  {
    id: 7,
    author: 'Веласкес',
    name: 'Вилла Медичи в Риме. Полдень',
    year: '1630',
    image: './src/img/landscapes/7.jpg',
  },
  {
    id: 8,
    author: 'Иван Шишкин',
    name: 'Утро в сосновом лесу',
    year: '1889',
    image: './src/img/landscapes/8.jpg',
  },
  {
    id: 9,
    author: 'Алексей Саврасов',
    name: 'Грачи прилетели',
    year: '1871',
    image: './src/img/landscapes/9.jpg',
  },
  {
    id: 10,
    author: 'Ян Вермеер',
    name: 'Улочка',
    year: '1658',
    image: './src/img/landscapes/10.jpg',
  },
  {
    id: 11,
    author: 'Исаак Левитан',
    name: 'Над вечным покоем',
    year: '1894',
    image: './src/img/landscapes/11.jpg',
  },
  {
    id: 12,
    author: 'Алексей Венецианов',
    name: 'На пашне. Весна',
    year: '1820',
    image: './src/img/landscapes/12.jpg',
  },
  {
    id: 13,
    author: 'Александр Иванов',
    name: 'Ветка',
    year: '1850',
    image: './src/img/landscapes/13.jpg',
  },
  {
    id: 14,
    author: 'Илья Репин',
    name: 'Летний пейзаж',
    year: '1879',
    image: './src/img/landscapes/14.jpg',
  },
  {
    id: 15,
    author: 'Клод Жозеф Верне',
    name: 'Морской порт при лунном свете',
    year: '1771',
    image: './src/img/landscapes/15.jpg',
  },
  {
    id: 16,
    author: 'Жан-Оноре Фрагонар',
    name: 'Водопой',
    year: '1765',
    image: './src/img/landscapes/16.jpg',
  },
  {
    id: 17,
    author: 'Каналетто',
    name: 'Вестминстерский мост в Лондоне',
    year: '1746',
    image: './src/img/landscapes/17.jpg',
  },
  {
    id: 18,
    author: 'Пьер Огюст Ренуар',
    name: 'Мост в Шату',
    year: '1875',
    image: './src/img/landscapes/18.jpg',
  },
  {
    id: 19,
    author: 'Франсуа Буше',
    name: 'Пейзаж в окрестностях Бове',
    year: '1740',
    image: './src/img/landscapes/19.jpg',
  },
  {
    id: 20,
    author: 'Константин Маковский',
    name: 'Перемещение ковра Мухаммеда из Мекки в Каир',
    year: '1875',
    image: './src/img/landscapes/20.jpg',
  },
  {
    id: 21,
    author: 'Питер Брейгель',
    name: 'Охотники на снегу',
    year: '1565',
    image: './src/img/landscapes/21.jpg',
  },
  {
    id: 22,
    author: 'Поль Сезанн',
    name: 'Гора св. Виктории со стороны окрестностей Гарданны',
    year: '1890',
    image: './src/img/landscapes/22.jpg',
  },
  {
    id: 23,
    author: 'Джон Констебл',
    name: 'Вид на собор в Солсбери из епископского сада',
    year: '1823',
    image: './src/img/landscapes/23.jpg',
  },
  {
    id: 24,
    author: 'Винсент Ван Гог',
    name: 'Звёздная ночь',
    year: '1889',
    image: './src/img/landscapes/24.jpg',
  },
  {
    id: 25,
    author: 'Жорж-Пьер Сёра',
    name: 'Дробильщик камня',
    year: '1882',
    image: './src/img/landscapes/25.jpg',
  },
  {
    id: 26,
    author: 'Жюль Дюпре',
    name: 'Старый дуб',
    year: '1870',
    image: './src/img/landscapes/26.jpg',
  },
  {
    id: 27,
    author: 'Марианна Верёвкина',
    name: 'Муравейник',
    year: '1916',
    image: './src/img/landscapes/27.jpg',
  },
  {
    id: 28,
    author: 'Николай Рерих',
    name: 'Горная обитель',
    year: '1933',
    image: './src/img/landscapes/28.jpg',
  },
  {
    id: 29,
    author: 'Клод Моне',
    name: 'Мост Ватерлоо, туман',
    year: '1903',
    image: './src/img/landscapes/29.jpg',
  },
  {
    id: 30,
    author: 'Иван Айвазовский',
    name: 'Буря на море',
    year: '1873',
    image: './src/img/landscapes/30.jpg',
  },
];

export default imageslandscapes;

