let mythology = [
  {
    id: 1,
    author: 'Тициан',
    name: 'Даная',
    year: '1560',
    image: './src/img/mythology/1.jpg',
  },
  {
    id: 2,
    author: 'Питер Пауль Рубенс',
    name: 'Союз Земли и Воды',
    year: '1618',
    image: './src/img/mythology/2.jpg',
  },
  {
    id: 3,
    author: 'Караваджо',
    name: 'Больной вакх',
    year: '1593',
    image: './src/img/mythology/3.jpg',
  },
  {
    id: 4,
    author: 'Виктор Васнецов',
    name: 'Иван-царевич на Сером Волке',
    year: '1888',
    image: './src/img/mythology/4.jpg',
  },
  {
    id: 5,
    author: 'Жак Луи Давид',
    name: 'Любовь Париса и Елены',
    year: '1788',
    image: './src/img/mythology/4.jpg',
  },
  {
    id: 6,
    author: 'Никола Пуссен',
    name: 'Пейзаж с Орфеем и Эвридикой',
    year: '1650',
    image: './src/img/mythology/6.jpg',
  },
  {
    id: 7,
    author: 'Рембрандт',
    name: 'Похищение Европы',
    year: '1632',
    image: './src/img/mythology/7.jpg',
  },
  {
    id: 8,
    author: 'Корреджо',
    name: 'Даная',
    year: '1530',
    image: './src/img/mythology/8.jpg',
  },
  {
    id: 9,
    author: 'Иероним Босх',
    name: 'Сад земных наслаждений',
    year: '1510',
    image: './src/img/mythology/9.jpg',
  },
  {
    id: 10,
    author: 'Жан Огюст Энгр',
    name: 'Эдип и Сфинкс',
    year: '1827',
    image: './src/img/mythology/10.jpg',
  },
  {
    id: 11,
    author: 'Илья Репин',
    name: 'Садко',
    year: '1876',
    image: './src/img/mythology/11.jpg',
  },
  {
    id: 12,
    author: 'Франсуа Буше',
    name: 'Купание Дианы',
    year: '1742',
    image: './src/img/mythology/12.jpg',
  },
  {
    id: 13,
    author: 'Джорджоне да Кастельфранко',
    name: 'Спящая Венера',
    year: '1510',
    image: './src/img/mythology/13.jpg',
  },
  {
    id: 14,
    author: 'Диего Веласкес',
    name: 'Венера с зеркалом',
    year: '1651',
    image: './src/img/mythology/14.jpg',
  },
  {
    id: 15,
    author: 'Франсиско Гойя',
    name: 'Сатурн, пожирающий своего сына',
    year: '1823',
    image: './src/img/mythology/15.jpg',
  },
  {
    id: 16,
    author: 'Рафаэль',
    name: 'Триумф Галатеи',
    year: '1512',
    image: './src/img/mythology/16.jpg',
  },
  {
    id: 17,
    author: 'Джон Уильям Уотерхаус',
    name: 'Волшебница Шалот',
    year: '1888',
    image: './src/img/mythology/17.jpg',
  },
  {
    id: 18,
    author: 'Питер Брейгель-Старший',
    name: 'Падение Икара',
    year: '1560',
    image: './src/img/mythology/18.jpg',
  },
  {
    id: 19,
    author: 'Веронезе',
    name: 'Марс и Венера',
    year: '1560',
    image: './src/img/mythology/19.jpg',
  },
  {
    id: 20,
    author: 'Жак-Луи Давид',
    name: 'Клятва Горациев',
    year: '1784',
    image: './src/img/mythology/20.jpg',
  },
  {
    id: 21,
    author: 'Николя Пуссен',
    name: 'Танец под Музыку Времени',
    year: '1636',
    image: './src/img/mythology/21.jpg',
  },
  {
    id: 22,
    author: 'Вильям-Адольф Бугро',
    name: 'Нимфы и Сатир',
    year: '1873',
    image: './src/img/mythology/22.jpg',
  },
  {
    id: 23,
    author: 'Антонио дель Поллайоло',
    name: 'Геракл и Гидра',
    year: '1475',
    image: './src/img/mythology/23.jpg',
  },
  {
    id: 24,
    author: 'Геркулес и Омфала',
    name: 'Доссо Досси',
    year: '1535',
    image: './src/img/mythology/24.jpg',
  },
  {
    id: 25,
    author: 'Сальватор Роза',
    name: 'Речной пейзаж с Аполлоном и Кумской сивиллой',
    year: '1665',
    image: './src/img/mythology/25.jpg',
  },
  {
    id: 26,
    author: 'Сандро Боттичелли',
    name: 'Весна',
    year: '1482',
    image: './src/img/mythology/26.jpg',
  },
  {
    id: 27,
    author: 'Адольф Вильям Бугро',
    name: 'Девушка и Амур',
    year: '1880',
    image: './src/img/mythology/27.jpg',
  },
  {
    id: 28,
    author: 'Луи Лагрене',
    name: 'Марс и Венера',
    year: '1770',
    image: './src/img/mythology/28.jpg',
  },
  {
    id: 29,
    author: 'Анн-Луи Жироде-Триозон',
    name: 'Сон Эндимиона',
    year: '1791',
    image: './src/img/mythology/29.jpg',
  },
  {
    id: 30,
    author: 'Уильям Блейк ',
    name: 'Геката',
    year: '1795',
    image: './src/img/mythology/30.jpg',
  },
]

export default mythology;