let mythology = [
  {
    id: 1,
    author: 'Рафаэль',
    name: 'Святой Георгий и дракон',
    year: '1506',
    image: './src/img/mythology/1.jpg',
  },
  {
    id: 2,
    author: 'Питер Пауль Рубенс',
    name: 'Союз Земли и Воды',
    year: '1618',
    image: './src/img/mythology/2.jpg',
  },
  {
    id: 3,
    author: 'Караваджо',
    name: 'Больной вакх',
    year: '1593',
    image: './src/img/mythology/3.jpg',
  },
  {
    id: 4,
    author: 'Виктор Васнецов',
    name: 'Иван-царевич на Сером Волке',
    year: '1888',
    image: './src/img/mythology/4.jpg',
  },
  {
    id: 5,
    author: 'Питер Пауль Рубенс',
    name: 'Похищение Орфии Бореем',
    image: './src/img/mythology/4.jpg',
  },
  {
    id: 6,
    author: 'Питер Пауль Рубенс',
    name: 'Похищение дочерей Левкиппа',
    year: '1618',
    image: './src/img/mythology/6.jpg',
  },
  {
    id: 7,
    author: 'Рембрандт',
    name: 'Похищение Европы',
    year: '1632',
    image: './src/img/mythology/7.jpg',
  },
  {
    id: 8,
    author: 'Корреджо',
    name: 'Даная',
    year: '1530',
    image: './src/img/mythology/8.jpg',
  },
  {
    id: 9,
    author: 'Иероним Босх',
    name: 'Сад земных наслаждений',
    year: '1510',
    image: './src/img/mythology/9.jpg',
  },
  {
    id: 10,
    author: 'Рембрандт',
    name: 'Даная',
    year: '1647',
    image: './src/img/mythology/10.jpg',
  },
  {
    id: 11,
    author: 'Илья Репин',
    name: 'Садко',
    year: '1876',
    image: './src/img/mythology/11.jpg',
  },
  {
    id: 12,
    author: 'Франсуа Буше',
    name: 'Купание Дианы',
    year: '1742',
    image: './src/img/mythology/12.jpg',
  },
  {
    id: 13,
    author: 'Рембрандт',
    name: 'Пир Вальтасара',
    year: '1635',
    image: './src/img/mythology/13.jpg',
  },
  {
    id: 14,
    author: 'Веласкес',
    name: 'Венера с зеркалом',
    year: '1651',
    image: './src/img/mythology/14.jpg',
  },
  {
    id: 15,
    author: 'Франсуа Буше',
    name: 'Четыре сезона - Весна',
    year: '1755',
    image: './src/img/mythology/15.jpg',
  },
  {
    id: 16,
    author: 'Рафаэль',
    name: 'Триумф Галатеи',
    year: '1512',
    image: './src/img/mythology/16.jpg',
  },
  {
    id: 17,
    author: 'Джон Уильям Уотерхаус',
    name: 'Волшебница Шалот',
    year: '1888',
    image: './src/img/mythology/17.jpg',
  },
  {
    id: 18,
    author: 'Виктор Васнецов',
    name: 'Три царевны подземного царства',
    year: '1884',
    image: './src/img/mythology/18.jpg',
  },
  {
    id: 19,
    author: 'Веронезе',
    name: 'Марс и Венера',
    year: '1560',
    image: './src/img/mythology/19.jpg',
  },
  {
    id: 20,
    author: 'Жак-Луи Давид',
    name: 'Клятва Горациев',
    year: '1784',
    image: './src/img/mythology/20.jpg',
  },
  {
    id: 21,
    author: 'Питер Пауль Рубенс',
    name: 'Персей освобождает Андромеду',
    year: '1622',
    image: './src/img/mythology/21.jpg',
  },
  {
    id: 22,
    author: 'Виктор Васнецов',
    name: 'Ковер-самолёт',
    year: '1880',
    image: './src/img/mythology/22.jpg',
  },
  {
    id: 23,
    author: 'Антонио дель Поллайоло',
    name: 'Геракл и Гидра',
    year: '1475',
    image: './src/img/mythology/23.jpg',
  },
  {
    id: 24,
    author: 'Илья Репин',
    name: 'Запорожцы',
    year: '1891',
    image: './src/img/mythology/24.jpg',
  },
  {
    id: 25,
    author: 'Веласкес',
    name: 'Кузница вулкана',
    year: '1630',
    image: './src/img/mythology/25.jpg',
  },
  {
    id: 26,
    author: 'Сандро Боттичелли',
    name: 'Весна',
    year: '1482',
    image: './src/img/mythology/26.jpg',
  },
  {
    id: 27,
    author: 'Адольф Вильям Бугро',
    name: 'Девушка и Амур',
    year: '1880',
    image: './src/img/mythology/27.jpg',
  },
  {
    id: 28,
    author: 'Луи Лагрене',
    name: 'Марс и Венера',
    year: '1770',
    image: './src/img/mythology/28.jpg',
  },
  {
    id: 29,
    author: 'Караваджо',
    name: 'Обращение Савла',
    year: '1601',
    image: './src/img/mythology/29.jpg',
  },
  {
    id: 30,
    author: 'Виктор Васнецов',
    name: 'Аленушка',
    year: '1881',
    image: './src/img/mythology/30.jpg',
  },
]

export default mythology;