let epochs =  [
  {
    id: 1,
    author: 'Питер Пауль Рубенс',
    name: 'Четыре части света',
    year: '1615',
    image: './src/img/epochs/1.jpg',
  },
  {
    id: 2,
    author: 'Антонис ван Дейк',
    name: 'Семейный портрет',
    year: '1621',
    image: './src/img/epochs/2.jpg',
  },
  {
    id: 3,
    author: 'Караваджо',
    name: 'Лютнист',
    year: '1595',
    image: './src/img/epochs/3.jpg',
  },
  {
    id: 4,
    author: 'Никола Пуссен',
    name: 'Танец под музыку времени',
    year: '1636',
    image: './src/img/epochs/4.jpg',
  },
  {
    id: 5,
    author: 'Рембрандт',
    name: 'Ночной дозор',
    year: '1642',
    image: './src/img/epochs/5.jpg',
  },
  {
    id: 6,
    author: 'Ян Вермеер',
    name: 'Девушка с жемчужной серёжкой',
    year: '1665',
    image: './src/img/epochs/6.jpg',
  },
  {
    id: 7,
    author: 'Франс Халс',
    name: 'Встреча офицеров и сержантов Каливерменской гражданской гвардии (членов стрелкового ополчения Св. Адриана)',
    year: '1633',
    image: './src/img/epochs/7.jpg',
  },
  {
    id: 8,
    author: 'Франс Снейдерс',
    name: 'Натюрморт с ведёрком для охлаждения вина',
    year: '1620',
    image: './src/img/epochs/8.jpg',
  },
  {
    id: 9,
    author: 'Якоб Йорданс',
    name: 'Бобовый король',
    year: '1640',
    image: './src/img/epochs/9.jpg',
  },
  {
    id: 10,
    author: 'Диего Веласкес',
    name: 'Менины',
    year: '1656',
    image: './src/img/epochs/10.jpg',
  },
  {
    id: 11,
    author: 'Жан-Оноре Фрагонар',
    name: 'Счастливые возможности качелей',
    year: '1768',
    image: './src/img/epochs/11.jpg',
  },
  {
    id: 12,
    author: 'Антуан Ватто',
    name: 'Отплытие с Киферы',
    year: '1717',
    image: './src/img/epochs/12.jpg',
  },
  {
    id: 13,
    author: 'Франсуа Буше',
    name: 'Завтрак',
    year: '1739',
    image: './src/img/epochs/13.jpg',
  },
  {
    id: 14,
    author: 'Джованни Баттиста Тьеполо',
    name: 'Аллегория планет и континентов',
    year: '1752',
    image: './src/img/epochs/14.jpg',
  },
  {
    id: 15,
    author: 'Каналетто',
    name: 'Возвращение Бучинторо к молу у Дворца дожей',
    year: '1730',
    image: './src/img/epochs/15.jpg',
  },
  {
    id: 16,
    author: 'Антон Лосенко',
    name: 'Прощание Гектора с Андромахой',
    year: '1773',
    image: './src/img/epochs/16.jpg',
  },
  {
    id: 17,
    author: 'Фёдор Рокотов',
    name: 'Коронационный портрет Екатерины II',
    year: '1763',
    image: './src/img/epochs/17.jpg',
  },
  {
    id: 18,
    author: 'Тициан',
    name: 'Венера Урбинская',
    year: '1538',
    image: './src/img/epochs/18.jpg',
  },
  {
    id: 19,
    author: 'Орацио Джентилески',
    name: 'Даная',
    year: '1621',
    image: './src/img/epochs/19.jpg',
  },
  {
    id: 20,
    author: 'Уильям Хогарт',
    name: 'Брачный контракт',
    year: '1745',
    image: './src/img/epochs/20.jpg',
  },
  {
    id: 21,
    author: 'Томас Гейнсборо',
    name: 'Мистер и миссис Эндрюс',
    year: '1750',
    image: './src/img/epochs/21.jpg',
  },
  {
    id: 22,
    author: '',
    name: '',
    year: '',
    image: './src/img/epochs/22.jpg',
  },
  {
    id: 23,
    author: 'Джошуа Рейнольдс',
    name: 'Младенец Геракл, удушающий змей, подосланных Герой',
    year: '1786',
    image: './src/img/epochs/23.jpg',
  },
  {
    id: 24,
    author: 'Геррит ван Хонтхорст',
    name: 'Пьяный скрипач',
    year: '1623',
    image: './src/img/epochs/24.jpg',
  },
  {
    id: 25,
    author: 'Михил Миревелт',
    name: 'Урок анатомии',
    year: '1617',
    image: './src/img/epochs/25.jpg',
  },
  {
    id: 26,
    author: 'Эль Греко',
    name: 'Вид Толедо',
    year: '1600',
    image: './src/img/epochs/26.jpg',
  },
  {
    id: 27,
    author: 'Жак Луи Давид',
    name: 'Клятва Горациев',
    year: '1784',
    image: './src/img/epochs/27.jpg',
  },
  {
    id: 28,
    author: 'Владимир Боровиковский',
    name: 'Екатерина II на прогулке в Царскосельском парке',
    year: '1794',
    image: './src/img/epochs/28.jpg',
  },
  {
    id: 29,
    author: 'Питер де Хох',
    name: 'Женщина с ребёнком у кладовки',
    year: '1658',
    image: './src/img/epochs/29.jpg',
  },
  {
    id: 30,
    author: 'Герард Терборх',
    name: 'Бокал лимонада',
    year: '1664',
    image: './src/img/epochs/30.jpg',
  },
]

export default epochs;



