let imagesPortraints = [
  {
    id: 1,
    author: 'Владимир Боровиковский',
    name: 'Портрет Лопухиной',
    year: '1797',
    image: './src/img/portraints/1.jpg',
  },
  {
    id: 2,
    author: 'Леонардо да Винчи',
    name: 'Дама с горностаем',
    year: '1490',
    image: './src/img/portraints/2.jpg',
  },
  {
    id: 3,
    author: 'Веласкес',
    name: 'Инфанта Маргарита',
    year: '1654',
    image: './src/img/portraints/3.jpg',
  },
  {
    id: 4,
    author: 'Константин Маковский',
    name: 'Портрет графини Софьи',
    year: '1890',
    image: './src/img/portraints/4.jpg',
  },
  {
    id: 5,
    author: 'Ян Вермеер',
    name: 'Девушка с жемчужной серёжкой',
    year: '1665',
    image: './src/img/portraints/5.jpg',
  },
  {
    id: 6,
    author: 'Карл Брюллов',
    name: 'Автопортрет',
    year: '1848',
    image: './src/img/portraints/6.jpg',
  },
  {
    id: 7,
    author: 'Гейнсборо',
    name: 'Дама в голубом',
    year: '1780',
    image: './src/img/portraints/7.jpg',
  },
  {
    id: 8,
    author: 'Рембрандт',
    name: 'Автопортрет с Саскией',
    year: '1635',
    image: './src/img/portraints/8.jpg',
  },
  {
    id: 9,
    author: 'Леонардо да Винчи',
    name: 'Мона Лиза',
    year: '1505',
    image: './src/img/portraints/9.jpg',
  },
  {
    id: 10,
    author: 'Иван Крамской',
    name: 'Неизвестная',
    year: '1883',
    image: './src/img/portraints/10.jpg',
  },
  {
    id: 11,
    author: 'Винсент Ван Гог',
    name: 'Автопортрет с перевязанным ухом',
    year: '1889',
    image: './src/img/portraints/11.jpg',
  },
  {
    id: 12,
    author: 'Рафаэль',
    name: 'Дама с единорогом',
    year: '1506',
    image: './src/img/portraints/12.jpg',
  },
  {
    id: 13,
    author: 'Эжен Делакруа',
    name: 'Автопортрет',
    year: '1837',
    image: './src/img/portraints/13.jpg',
  },
  {
    id: 14,
    author: 'Карл Брюллов',
    name: 'Автопортрет',
    year: '1848',
    image: './src/img/portraints/14.jpg',
  },
  {
    id: 15,
    author: 'Пьер Огюст Ренуар',
    name: 'Портрет Жанны Самари',
    year: '1877',
    image: './src/img/portraints/15.jpg',
  },
  {
    id: 16,
    author: 'Валентин Серов',
    name: 'Девочка с персиками',
    year: '1887',
    image: './src/img/portraints/16.jpg',
  },
  {
    id: 17,
    author: 'Василий Тропинин',
    name: 'Девушка с горшком роз',
    year: '1850',
    image: './src/img/portraints/17.jpg',
  },
  {
    id: 18,
    author: 'Ян ван Эйк',
    name: 'Портрет четы Арнольфини',
    year: '1434',
    image: './src/img/portraints/18.jpg',
  },
  {
    id: 19,
    author: 'Орест Кипренский',
    name: 'Портрет А. Пушкина',
    year: '1827',
    image: './src/img/portraints/19.jpg',
  },
  {
    id: 20,
    author: 'Виктор Васнецов',
    name: 'Царь Иван Васильевич Грозный',
    year: '1896',
    image: './src/img/portraints/20.jpg',
  },
  {
    id: 21,
    author: 'Василий Перов',
    name: 'Портрет Ф. Достоевского',
    year: '1872',
    image: './src/img/portraints/21.jpg',
  },
  {
    id: 22,
    author: 'Зинаида Серебрякова',
    name: 'Портрет О. Лансере',
    year: '1910',
    image: './src/img/portraints/22.jpg',
  },
  {
    id: 23,
    author: 'Густав Климт',
    name: 'Портрет Адели Блох-Бауэр I',
    year: '1907',
    image: './src/img/portraints/23.jpg',
  },
  {
    id: 24,
    author: 'Ганс Гольбейн',
    name: 'Портрет короля Генриха VIII',
    year: '1540',
    image: './src/img/portraints/24.jpg',
  },
  {
    id: 25,
    author: 'Илья Репин',
    name: 'Портрет писателя Л. Толстого',
    year: '1887',
    image: './src/img/portraints/25.jpg',
  },
  {
    id: 26,
    author: 'Карл Брюллов',
    name: 'Всадница',
    year: '1832',
    image: './src/img/portraints/26.jpg',
  },
  {
    id: 27,
    author: 'Зинаида Серебрякова',
    name: 'За туалетом. Автопортрет',
    year: '1909',
    image: './src/img/portraints/27.jpg',
  },
  {
    id: 28,
    author: 'Борис Кустодиев',
    name: 'Купчиха за чаем',
    year: '1918',
    image: './src/img/portraints/28.jpg',
  },
  {
    id: 29,
    author: 'Питер Пауль Рубенс',
    name: 'Потрет камеристки инфанты Изабеллы',
    year: '1625',
    image: './src/img/portraints/29.jpg',
  },
  {
    id: 30,
    author: 'Карл Брюллов',
    name: 'Итальянский полдень',
    year: '1827',
    image: './src/img/portraints/30.jpg',
  },
];

export default imagesPortraints;