let imagesPortraints = [
  [
    {
      id: 1,
      author: 'Владимир Боровиковский',
      name: 'Портрет Лопухиной',
      year: '1797',
      image: './src/img/portraints/1.jpg',
    },
    {
      id: 2,
      author: 'Петрус Кристус',
      name: 'Портрет девушки',
      year: '1470',
      image: './src/img/portraints/2.jpg',
    },
    {
      id: 3,
      author: 'Веласкес',
      name: 'Инфанта Маргарита',
      year: '1654',
      image: './src/img/portraints/3.jpg',
    },
    {
      id: 4,
      author: 'Константин Маковский',
      name: 'Портрет графини Софьи',
      year: '1890',
      image: './src/img/portraints/4.jpg',
    },
    {
      id: 5,
      author: 'Ян Вермеер',
      name: 'Девушка с жемчужной серёжкой',
      year: '1665',
      image: './src/img/portraints/5.jpg',
    },
    {
      id: 6,
      author: 'Карл Брюллов',
      name: 'Автопортрет',
      year: '1848',
      image: './src/img/portraints/6.jpg',
    },
    {
      id: 7,
      author: 'Гейнсборо',
      name: 'Дама в голубом',
      year: '1780',
      image: './src/img/portraints/7.jpg',
    },
    {
      id: 8,
      author: 'Рембрандт',
      name: 'Автопортрет с Саскией',
      year: '1635',
      image: './src/img/portraints/8.jpg',
    },
    {
      id: 9,
      author: 'Леонардо да Винчи',
      name: 'Мона Лиза',
      year: '1505',
      image: './src/img/portraints/9.jpg',
    },
    {
      id: 10,
      author: 'Иван Крамской',
      name: 'Неизвестная',
      year: '1883',
      image: './src/img/portraints/10.jpg',
    },
    {
      id: 11,
      author: 'Винсент Ван Гог',
      name: 'Автопортрет с перевязанным ухом',
      year: '1889',
      image: './src/img/portraints/11.jpg',
    },
    {
      id: 12,
      author: 'Рафаэль',
      name: 'Дама с единорогом',
      year: '1506',
      image: './src/img/portraints/12.jpg',
    },
    {
      id: 13,
      author: 'Эжен Делакруа',
      name: 'Автопортрет',
      year: '1837',
      image: './src/img/portraints/13.jpg',
    },
    {
      id: 14,
      author: 'Карл Брюллов',
      name: 'Автопортрет',
      year: '1848',
      image: './src/img/portraints/14.jpg',
    },
    {
      id: 15,
      author: 'Пьер Огюст Ренуар',
      name: 'Портрет Жанны Самари',
      year: '1877',
      image: './src/img/portraints/15.jpg',
    },
    {
      id: 16,
      author: 'Валентин Серов',
      name: 'Девочка с персиками',
      year: '1887',
      image: './src/img/portraints/16.jpg',
    },
    {
      id: 17,
      author: 'Василий Тропинин',
      name: 'Девушка с горшком роз',
      year: '1850',
      image: './src/img/portraints/17.jpg',
    },
    {
      id: 18,
      author: 'Ян ван Эйк',
      name: 'Портрет четы Арнольфини',
      year: '1434',
      image: './src/img/portraints/18.jpg',
    },
    {
      id: 19,
      author: 'Орест Кипренский',
      name: 'Портрет А. Пушкина',
      year: '1827',
      image: './src/img/portraints/19.jpg',
    },
    {
      id: 20,
      author: 'Виктор Васнецов',
      name: 'Царь Иван Васильевич Грозный',
      year: '1896',
      image: './src/img/portraints/20.jpg',
    },
    {
      id: 21,
      author: 'Василий Перов',
      name: 'Портрет Ф. Достоевского',
      year: '1872',
      image: './src/img/portraints/21.jpg',
    },
    {
      id: 22,
      author: 'Рогир ван дер Вейден',
      name: 'Портрет дамы',
      year: '1460',
      image: './src/img/portraints/22.jpg',
    },
    {
      id: 23,
      author: 'Густав Климт',
      name: 'Портрет Адели Блох-Бауэр I',
      year: '1907',
      image: './src/img/portraints/23.jpg',
    },
    {
      id: 24,
      author: 'Ганс Гольбейн',
      name: 'Портрет короля Генриха VIII',
      year: '1540',
      image: './src/img/portraints/24.jpg',
    },
    {
      id: 25,
      author: 'Илья Репин',
      name: 'Портрет писателя Л. Толстого',
      year: '1887',
      image: './src/img/portraints/25.jpg',
    },
    {
      id: 26,
      author: 'Альбрехт Дюрер',
      name: 'Автопортрет',
      year: '1500',
      image: './src/img/portraints/26.jpg',
    },
    {
      id: 27,
      author: 'Зинаида Серебрякова',
      name: 'За туалетом. Автопортрет',
      year: '1909',
      image: './src/img/portraints/27.jpg',
    },
    {
      id: 28,
      author: 'Борис Кустодиев',
      name: 'Купчиха за чаем',
      year: '1918',
      image: './src/img/portraints/28.jpg',
    },
    {
      id: 29,
      author: 'Питер Пауль Рубенс',
      name: 'Потрет камеристки инфанты Изабеллы',
      year: '1625',
      image: './src/img/portraints/29.jpg',
    },
    {
      id: 30,
      author: 'Тициан',
      name: 'Портрет Федерико II Гонзага',
      year: '1529',
      image: './src/img/portraints/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Пабло Пикассо',
      name: 'Дружба',
      year: '1908',
      image: './src/img/art20th/1.jpg',
    },
    {
      id: 2,
      author: 'Николай Рерих',
      name: 'Горная обитель',
      year: '1933',
      image: './src/img/art20th/2.jpg',
    },
    {
      id: 3,
      author: 'Жорж Брак',
      name: 'Скрипка и подсвечник',
      year: '1910',
      image: './src/img/art20th/3.jpg',
    },
    {
      id: 4,
      author: 'Марианна Верёвкина',
      name: 'Осень, школа',
      year: '1907',
      image: './src/img/art20th/4.jpg',
    },
    {
      id: 5,
      author: 'Наталия Гончарова',
      name: 'Фабрика',
      year: '1922',
      image: './src/img/art20th/5.jpg',
    },
    {
      id: 6,
      author: 'Джакомо Балла',
      name: 'Скорость + звук',
      year: '1914',
      image: './src/img/art20th/6.jpg',
    },
    {
      id: 7,
      author: 'Гаэтано Превиати',
      name: 'Пейзаж',
      year: '1905',
      image: './src/img/art20th/7.jpg',
    },
    {
      id: 8,
      author: 'Казимир Малевич',
      name: 'Черный квадрат',
      year: '1915',
      image: './src/img/art20th/8.jpg',
    },
    {
      id: 9,
      author: 'Сальвадор Дали',
      name: 'Сон, вызванный полётом пчелы вокруг граната, за секунду до пробуждения',
      year: '1944',
      image: './src/img/art20th/9.jpg',
    },
    {
      id: 10,
      author: 'Василий Кандинский',
      name: 'Композиция VIII',
      year: '1923',
      image: './src/img/art20th/10.jpg',
    },
    {
      id: 11,
      author: 'Густав Климт',
      name: 'Поцелуй',
      year: '1908',
      image: './src/img/art20th/11.jpg',
    },
    {
      id: 12,
      author: 'Кузьма Петров-Водкин',
      name: 'Купание красного коня',
      year: '1912',
      image: './src/img/art20th/12.jpg',
    },
    {
      id: 13,
      author: 'Энди Уорхол',
      name: 'Банки супа «Кэмпбелл»',
      year: '1962',
      image: './src/img/art20th/13.jpg',
    },
    {
      id: 14,
      author: 'Жоан Миро',
      name: 'Карнавал Арлекина',
      year: '1925',
      image: './src/img/art20th/14.jpg',
    },
    {
      id: 15,
      author: 'Макс Пехштейн',
      name: 'Под деревьями (Ню на пленэре)',
      year: '1911',
      image: './src/img/art20th/15.jpg',
    },
    {
      id: 16,
      author: 'Марк Шагал',
      name: 'Прогулка',
      year: '1918',
      image: './src/img/art20th/16.jpg',
    },
    {
      id: 17,
      author: 'Анри Матисс',
      name: 'Танец',
      year: '1910',
      image: './src/img/art20th/17.jpg',
    },
    {
      id: 18,
      author: 'Рене Магритт',
      name: 'Сын человеческий',
      year: '1964',
      image: './src/img/art20th/18.jpg',
    },
    {
      id: 19,
      author: 'Андре Дерен',
      name: 'Мост Чаринг-Кросс',
      year: '1906',
      image: './src/img/art20th/19.jpg',
    },
    {
      id: 20,
      author: 'Джексон Поллок.',
      name: 'Лавандовый туман (Номер 1)',
      year: '1950',
      image: './src/img/art20th/20.jpg',
    },
    {
      id: 21,
      author: 'Зинаида Серебрякова',
      name: 'За завтраком',
      year: '1914',
      image: './src/img/art20th/21.jpg',
    },
    {
      id: 22,
      author: 'Валентин Серов',
      name: 'Портрет княгини З. Н. Юсуповой',
      year: '1902',
      image: './src/img/art20th/22.jpg',
    },
    {
      id: 23,
      author: 'Борис Кустодиев',
      name: 'Купчиха за чаем',
      year: '1918',
      image: './src/img/art20th/23.jpg',
    },
    {
      id: 24,
      author: 'Максимильен Люс',
      name: 'Монмартр, улица Кортот, вид из Сен-Дени',
      year: '1900',
      image: './src/img/art20th/24.jpg',
    },
    {
      id: 25,
      author: 'Юрий Пименов',
      name: 'Лирическое новоселье', 
      year: '1965',
      image: './src/img/art20th/25.jpg',
    },
    {
      id: 26,
      author: 'Пит Мондриан',
      name: 'Композиция с красным, синим и жёлтым',
      year: '1930',
      image: './src/img/art20th/26.jpg',
    },
    {
      id: 27,
      author: 'Михаил Врубель',
      name: 'Шестикрылый серафим (Азраил)',
      year: '1904',
      image: './src/img/art20th/27.jpg',
    },
    {
      id: 28,
      author: 'Анри Руссо',
      name: 'Муза, вдохновляющая поэта',
      year: '1909',
      image: './src/img/art20th/28.jpg',
    },
    {
      id: 29,
      author: 'Август Макке',
      name: 'Дама в зеленом жакете',
      year: '1913',
      image: './src/img/art20th/29.jpg',
    },
    {
      id: 30,
      author: 'Андре Дерен',
      name: 'Мост Чаринг-Кросс',
      year: '1906',
      image: './src/img/art20th/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Вильгельм фон Каульбах',
      name: 'Разрушение Иерусалима',
      year: '1846',
      image: './src/img/art1-19/1.jpg',
    },
    {
      id: 2,
      author: 'Алексей Венецианов',
      name: 'Спящий пастушок',
      year: '1826',
      image: './src/img/art1-19/2.jpg',
    },
    {
      id: 3,
      author: 'Карл Брюллов',
      name: 'Всадница',
      year: '1832',
      image: './src/img/art1-19/3.jpg',
    },
    {
      id: 4,
      author: 'Василий Верещагин',
      name: 'Апофеоз войны',
      year: '1817',
      image: './src/img/art1-19/4.jpg',
    },
    {
      id: 5,
      author: 'Василий Тропинин',
      name: 'Девушка с горшком роз',
      year: '1850',
      image: './src/img/art1-19/5.jpg',
    },
    {
      id: 6,
      author: 'Карл Шпицвег',
      name: 'Бедный поэт',
      year: '1839',
      image: './src/img/art1-19/6.jpg',
    },
    {
      id: 7,
      author: 'Иван Айвазовский',
      name: 'Девятый вал',
      year: '1850',
      image: './src/img/art1-19/7.jpg',
    },
    {
      id: 8,
      author: 'Эжен Делакруа',
      name: 'Свобода, ведущая народ',
      year: '1830',
      image: './src/img/art1-19/8.jpg',
    },
    {
      id: 9,
      author: 'Жилло Сент-Эвр',
      name: 'Миранда играет в шахматы с Фердинандом, шутливо обвиняя его в обмане',
      year: '1822',
      image: './src/img/art1-19/9.jpg',
    },
    {
      id: 10,
      author: 'Франциско Гоя',
      name: 'Расстрел повстанцев',
      year: '1808',
      image: './src/img/art1-19/10.jpg',
    },
    {
      id: 11,
      author: 'Поль Деларош',
      name: 'Казнь Джейн Грей',
      year: '1833',
      image: './src/img/art1-19/11.jpg',
    },
    {
      id: 12,
      author: 'Джон Констебл',
      name: 'Вид на собор в Солсбери из епископского сада',
      year: '1823',
      image: './src/img/art1-19/12.jpg',
    },
    {
      id: 13,
      author: 'Марк Глейр',
      name: 'Танец вакханок',
      year: '1849',
      image: './src/img/art1-19/13.jpg',
    },
    {
      id: 14,
      author: 'Александр Иванов',
      name: 'Явление Христа Марии Магдалине после воскресения',
      year: '1835',
      image: './src/img/art1-19/14.jpg',
    },
    {
      id: 15,
      author: 'Фёдор Бруни',
      name: 'Медный змий',
      year: '1841',
      image: './src/img/art1-19/15.jpg',
    },
    {
      id: 16,
      author: 'Орест Кипренский',
      name: 'Портрет А. С. Пушкина',
      year: '1827',
      image: './src/img/art1-19/16.jpg',
    },
    {
      id: 17,
      author: 'Эмануэль Лойце',
      name: 'Вашингтон переправляется через Делавэр',
      year: '1851',
      image: './src/img/art1-19/17.jpg',
    },
    {
      id: 18,
      author: 'Жак Луи Давид',
      name: 'Бонапарт на перевале Сен-Бернар',
      year: '1801',
      image: './src/img/art1-19/18.jpg',
    },
    {
      id: 19,
      author: 'Василий Сазонов',
      name: 'Дмитрий Донской на Куликовом поле',
      year: '1824',
      image: './src/img/art1-19/19.jpg',
    },
    {
      id: 20,
      author: 'Каспар Давид Фридрих',
      name: 'Странник над морем тумана',
      year: '1818',
      image: './src/img/art1-19/20.jpg',
    },
    {
      id: 21,
      author: 'Фёдор  Матвеев',
      name: 'Вид Рима. Колизей',
      year: '1816',
      image: './src/img/art1-19/21.jpg',
    },
    {
      id: 22,
      author: 'Фридрих Амерлинг',
      name: 'Портрет Рудольфа фон Артхабера с детьми',
      year: '1837',
      image: './src/img/art1-19/22.jpg',
    },
    {
      id: 23,
      author: 'Фридрих Овербек',
      name: 'Италия и Германия',
      year: '1828 ',
      image: './src/img/art1-19/23.jpg',
    },
    {
      id: 24,
      author: 'Теодор Жерико',
      name: 'Плот «Медузы»',
      year: '1819',
      image: './src/img/art1-19/24.jpg',
    },
    {
      id: 25,
      author: 'Теодор Руссо',
      name: 'Рынок в Нормандии',
      year: '1830',
      image: './src/img/art1-19/25.jpg',
    },
    {
      id: 26,
      author: 'Уильям Тёрнер',
      name: 'Голландские лодки в шторм',
      year: '1801',
      image: './src/img/art1-19/26.jpg',
    },
    {
      id: 27,
      author: 'Густав Курбе',
      name: 'Похороны в Орнане',
      year: '1850',
      image: './src/img/art1-19/27.jpg',
    },
    {
      id: 28,
      author: 'Жан Франсуа Милле',
      name: 'Сеятель',
      year: '1850',
      image: './src/img/art1-19/28.jpg',
    },
    {
      id: 29,
      author: 'Жан Огюст Энгр',
      name: 'Большая одалиска',
      year: '1814',
      image: './src/img/art1-19/29.jpg',
    },
    {
      id: 30,
      author: 'Александр Кабанель',
      name: 'Падший ангел ',
      year: '1847',
      image: './src/img/art1-19/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Павел Федотов',
      name: 'Сватовство майора',
      year: '1852',
      image: './src/img/art2-19/1.jpg',
    },
    {
      id: 2,
      author: 'Эдгар Дега',
      name: 'Голубые танцовщицы',
      year: '1897',
      image: './src/img/art2-19/2.jpg',
    },
    {
      id: 3,
      author: 'Илья Репин',
      name: 'Иван Грозный и сын его Иван',
      year: '1885',
      image: './src/img/art2-19/3.jpg',
    },
    {
      id: 4,
      author: 'Константин Маковский',
      name: 'Портрет графини Софьи',
      year: '1890',
      image: './src/img/art2-19/4.jpg',
    },
    {
      id: 5,
      author: 'Уильям Хант',
      name: 'Пробудившийся стыд',
      year: '1853',
      image: './src/img/art2-19/5.jpg',
    },
    {
      id: 6,
      author: 'Пьер Огюст Ренуар',
      name: 'Прогулка в Булонском лесу',
      year: '1873',
      image: './src/img/art2-19/6.jpg',
    },
    {
      id: 7,
      author: 'Василий Поленов',
      name: 'Московский дворик',
      year: '1877',
      image: './src/img/art2-19/7.jpg',
    },
    {
      id: 8,
      author: 'Поль Сезанн',
      name: 'Пьеро и Арлекин',
      year: '1888',
      image: './src/img/art2-19/8.jpg',
    },
    {
      id: 9,
      author: 'Архип Куинджи',
      name: 'Берёзовая роща',
      year: '1879',
      image: './src/img/art2-19/9.jpg',
    },
    {
      id: 10,
      author: 'Поль Гоген',
      name: 'Откуда мы пришли? Кто мы? Куда мы идём?',
      year: '1898',
      image: './src/img/art2-19/10.jpg',
    },
    {
      id: 11,
      author: 'Уинслоу Хомер',
      name: 'Попутный ветер',
      year: '1876',
      image: './src/img/art2-19/11.jpg',
    },
    {
      id: 12,
      author: 'Иван Айвазовский',
      name: 'Волна',
      year: '1889',
      image: './src/img/art2-19/12.jpg',
    },
    {
      id: 13,
      author: 'Аксели Галлен-Каллела',
      name: 'Девушка на ветру',
      year: '1893',
      image: './src/img/art2-19/13.jpg',
    },
    {
      id: 14,
      author: 'Жорж-Пьер Сёра',
      name: 'Сена в Гранд-Жатт, весна',
      year: '1888',
      image: './src/img/art2-19/14.jpg',
    },
    {
      id: 15,
      author: 'Максимильен Люс',
      name: 'Порт Сен-Тропе',
      year: '1893',
      image: './src/img/art2-19/15.jpg',
    },
    {
      id: 16,
      author: 'Исаак Левитан',
      name: 'Весна – большая вода',
      year: '1897',
      image: './src/img/art2-19/16.jpg',
    },
    {
      id: 17,
      author: 'Клод Моне',
      name: 'Завтрак на траве',
      year: '1865',
      image: './src/img/art2-19/17.jpg',
    },
    {
      id: 18,
      author: 'Иван Шишкин',
      name: 'Сосновый бор',
      year: '1895',
      image: './src/img/art2-19/18.jpg',
    },
    {
      id: 19,
      author: 'Поль Синьяк',
      name: 'Порт Сен-Тропе',
      year: '1896',
      image: './src/img/art2-19/19.jpg',
    },
    {
      id: 20,
      author: 'Михаил Врубель',
      name: 'Демон сидящий',
      year: '1890',
      image: './src/img/art2-19/20.jpg',
    },
    {
      id: 21,
      author: 'Винсент Ван Гог',
      name: 'Ночное кафе в Арле',
      year: '1888',
      image: './src/img/art2-19/21.jpg',
    },
    {
      id: 22,
      author: 'Камиль Писсарро',
      name: 'Бульвар Монмартр в Париже',
      year: '1897',
      image: './src/img/art2-19/22.jpg',
    },
    {
      id: 23,
      author: 'Василий Суриков',
      name: 'Боярыня Морозова',
      year: '1887',
      image: './src/img/art2-19/23.jpg',
    },
    {
      id: 24,
      author: 'Адольф Вильям Бугро',
      name: 'Волна',
      year: '1896',
      image: './src/img/art2-19/24.jpg',
    },
    {
      id: 25,
      author: 'Василий Перов',
      name: 'Охотники на привале',
      year: '1871',
      image: './src/img/art2-19/25.jpg',
    },
    {
      id: 26,
      author: 'Михаил Нестеров',
      name: 'Видение отроку Варфоломею',
      year: '1890',
      image: './src/img/art2-19/26.jpg',
    },
    {
      id: 27,
      author: 'Алексей Саврасов',
      name: 'Грачи прилетели',
      year: '1871',
      image: './src/img/art2-19/27.jpg',
    },
    {
      id: 28,
      author: 'Анри де Тулуз-Лотрек',
      name: 'Угол Мулен де ла Галет',
      year: '1892',
      image: './src/img/art2-19/28.jpg',
    },
    {
      id: 29,
      author: 'Жюль Бастьен-Лепаж',
      name: 'Октябрь. Сбор картофеля',
      year: '1878',
      image: './src/img/art2-19/29.jpg',
    },
    {
      id: 30,
      author: 'Джон Милле',
      name: 'Офелия',
      year: '1852',
      image: './src/img/art2-19/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Рембрандт',
      name: 'Даная',
      year: '1647',
      image: './src/img/domestic/1.jpg',
    },
    {
      id: 2,
      author: 'Василий Перов',
      name: 'Приезд гувернантки в купеческий дом',
      year: '1866',
      image: './src/img/domestic/2.jpg',
    },
    {
      id: 3,
      author: 'Ян Вермеер',
      name: 'Хозяйка и служанка',
      year: '1667',
      image: './src/img/domestic/3.jpg',
    },
    {
      id: 4,
      author: 'Эдуард Мане',
      name: 'Ланч на траве',
      year: '1863',
      image: './src/img/domestic/4.jpg',
    },
    {
      id: 5,
      author: 'Бартоломео Мурильо',
      name: 'Мальчик с собакой',
      year: '1650',
      image: './src/img/domestic/5.jpg',
    },
    {
      id: 6,
      author: 'Юдит Лейстер',
      name: 'Весёлое трио',
      year: '1631',
      image: './src/img/domestic/6.jpg',
    },
    {
      id: 7,
      author: 'Корнелис Трост',
      name: 'Забавы в парке',
      year: '1740',
      image: './src/img/domestic/7.jpg',
    },
    {
      id: 8,
      author: 'Поль Гоген',
      name: 'Кафе в Арле',
      year: '1888',
      image: './src/img/domestic/8.jpg',
    },
    {
      id: 9,
      author: 'Пабло Пикассо',
      name: 'Любительница абсента',
      year: '1901',
      image: './src/img/domestic/9.jpg',
    },
    {
      id: 10,
      author: 'Питер Брейгель',
      name: 'Избиение младенцев',
      year: '1567',
      image: './src/img/domestic/10.jpg',
    },
    {
      id: 11,
      author: 'Караваджо',
      name: 'Лютнист',
      year: '1596',
      image: './src/img/domestic/11.jpg',
    },
    {
      id: 12,
      author: 'Пьер Огюст Ренуар',
      name: 'Бал в Мулен де ла Галетт',
      year: '1876',
      image: './src/img/domestic/12.jpg',
    },
    {
      id: 13,
      author: 'Винсент ван Гог',
      name: 'Воспоминание о саде в Эттене',
      year: '1888',
      image: './src/img/domestic/13.jpg',
    },
    {
      id: 14,
      author: 'Аксели Галлен-Каллела',
      name: 'Первый урок',
      year: '1889',
      image: './src/img/domestic/14.jpg',
    },
    {
      id: 15,
      author: 'Жан Батист Грёз',
      name: 'Избалованное дитя',
      year: '1765',
      image: './src/img/domestic/15.jpg',
    },
    {
      id: 16,
      author: 'Константин Маковский',
      name: 'Гадание',
      year: '1890',
      image: './src/img/domestic/16.jpg',
    },
    {
      id: 17,
      author: 'Павел Федотов',
      name: 'Завтрак аристократа',
      year: '1849',
      image: './src/img/domestic/17.jpg',
    },
    {
      id: 18,
      author: 'Татьяна Яблонская',
      name: 'Утро',
      year: '1954',
      image: './src/img/domestic/18.jpg',
    },
    {
      id: 19,
      author: 'Илья Репин',
      name: 'Не ждали',
      year: '1888',
      image: './src/img/domestic/19.jpg',
    },
    {
      id: 20,
      author: 'Алексей Венецианов',
      name: 'На жатве. Лето',
      year: '1827',
      image: './src/img/domestic/20.jpg',
    },
    {
      id: 21,
      author: 'Жан Фрагонар',
      name: 'Качели',
      year: '1767',
      image: './src/img/domestic/21.jpg',
    },
    {
      id: 22,
      author: 'Ян Стен',
      name: 'Семейный концерт',
      year: '1666',
      image: './src/img/domestic/22.jpg',
    },
    {
      id: 23,
      author: 'Томас Гейнсборо',
      name: 'Жатва. Возвращение с поля',
      year: '1767',
      image: './src/img/domestic/23.jpg',
    },
    {
      id: 24,
      author: 'Франсиско Гойя',
      name: 'Продажа керамической посуды',
      year: '1779',
      image: './src/img/domestic/24.jpg',
    },
    {
      id: 25,
      author: 'Оноре Домье',
      name: 'Шахматисты',
      year: '1867',
      image: './src/img/domestic/25.jpg',
    },
    {
      id: 26,
      author: 'Василий Петрович Верещагин',
      name: 'Великая княгиня Софья Витовтовна на свадьбе у великого князя Василия Тёмного…',
      year: '1861',
      image: './src/img/domestic/26.jpg',
    },
    {
      id: 27,
      author: 'Генри Скотт Тьюк',
      name: 'Все на помпу!',
      year: '1888',
      image: './src/img/domestic/27.jpg',
    },
    {
      id: 28,
      author: 'Клод Моне',
      name: 'Завтрак на траве',
      year: '1865',
      image: './src/img/domestic/28.jpg',
    },
    {
      id: 29,
      author: 'Джордж Беллоуз',
      name: 'Поединок Демпси и Фирпо',
      year: '1924',
      image: './src/img/domestic/28.jpg',
    },
    {
      id: 30,
      author: 'Гюстав Курбе',
      name: 'Бедная крестьянка зимой',
      year: '1866',
      image: './src/img/domestic/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Фредерик Бриджмен',
      name: 'Развлечение ассирийского царя',
      year: '1878',
      image: './src/img/historical/1.jpg',
    },
    {
      id: 2,
      author: 'Василий Суриков',
      name: 'Покорение Сибири Ермаком Тимофеевичем',
      year: '1895',
      image: './src/img/historical/2.jpg',
    },
    {
      id: 3,
      author: 'Рембрандт',
      name: 'Ночной дозор',
      year: '1642',
      image: './src/img/historical/3.jpg',
    },
    {
      id: 4,
      author: 'Пабло Пикассо',
      name: 'Герника',
      year: '1937',
      image: './src/img/historical/4.jpg',
    },
    {
      id: 5,
      author: 'Карл Брюллов',
      name: 'Последний день Помпеи',
      year: '1833',
      image: './src/img/historical/5.jpg',
    },
    {
      id: 6,
      author: 'Эжен Делакруа',
      name: 'Свобода, ведущая народ',
      year: '1830',
      image: './src/img/historical/6.jpg',
    },
    {
      id: 7,
      author: 'Константин Маковский',
      name: 'Перемещение ковра Мухаммеда из Мекки в Каир',
      year: '1875',
      image: './src/img/historical/7.jpg',
    },
    {
      id: 8,
      author: 'Илья Репин',
      name: 'Запорожцы',
      year: '1891',
      image: './src/img/historical/9.jpg',
    },
    {
      id: 9,
      author: 'Леонардо да Винчи',
      name: 'Тайная вечеря',
      year: '1498',
      image: './src/img/historical/8.jpg',
    },
    {
      id: 10,
      author: 'Гюстав Курбе',
      name: 'Мастерская художника',
      year: '1855',
      image: './src/img/historical/10.jpg',
    },
    {
      id: 11,
      author: 'Виктор Васнецов',
      name: 'Царь Иван Васильевич Грозный',
      year: '1896',
      image: './src/img/historical/11.jpg',
    },
    {
      id: 12,
      author: 'Франциско Гоя',
      name: 'Расстрел повстанцев',
      year: '1808',
      image: './src/img/historical/12.jpg',
    },
    {
      id: 13,
      author: 'Поль Деларош',
      name: 'Казнь Джейн Грей',
      year: '1833',
      image: './src/img/historical/13.jpg',
    },
    {
      id: 14,
      author: 'Веласкес',
      name: 'Сдача Бреды',
      year: '1635',
      image: './src/img/historical/14.jpg',
    },
    {
      id: 15,
      author: 'Эмануэль Лойце',
      name: 'Вашингтон переправляется через Делавэр',
      year: '1851',
      image: './src/img/historical/15.jpg',
    },
    {
      id: 16,
      author: 'Михаил Песков',
      name: 'Воззвание Минина к нижегородцам в 1611 году',
      year: '1861',
      image: './src/img/historical/16.jpg',
    },
    {
      id: 17,
      author: 'Фердинанда Лике',
      name: 'Набег викингов',
      year: '1906',
      image: './src/img/historical/17.jpg',
    },
    {
      id: 18,
      author: 'Вячеслав Шварца',
      name: 'Сцена из домашней жизни русских царей',
      year: '1865',
      image: './src/img/historical/18.jpg',
    },
    {
      id: 19,
      author: 'Жак-Луи Давид',
      name: 'Смерть Сократа',
      year: '1787',
      image: './src/img/historical/19.jpg',
    },
    {
      id: 20,
      author: 'Иван Айвазовский',
      name: 'Бриг «Меркурий», атакованный двумя турецкими кораблями',
      year: '1892',
      image: './src/img/historical/20.jpg',
    },
    {
      id: 21,
      author: 'Уильям Тёрнер',
      name: 'Трафальгарская битва',
      year: '1822',
      image: './src/img/historical/21.jpg',
    },
    {
      id: 22,
      author: 'Жак Луи Давид',
      name: 'Смерть Марата',
      year: '1793',
      image: './src/img/historical/22.jpg',
    },
    {
      id: 23,
      author: 'Андрей Петрович Рябушкин',
      name: 'Иоанн Грозный с приближёнными',
      year: '1903',
      image: './src/img/historical/23.jpg',
    },
    {
      id: 24,
      author: 'Валентин Серов',
      name: 'Коронация Николая II',
      year: '1896',
      image: './src/img/historical/24.jpg',
    },
    {
      id: 25,
      author: 'Пьеро делла Франческа',
      name: 'Молодой Геркулес',
      year: '1465',
      image: './src/img/historical/25.jpg',
    },
    {
      id: 26,
      author: 'Николя Пуссен',
      name: 'Смерть Германика',
      year: '1627',
      image: './src/img/historical/26.jpg',
    },
    {
      id: 27,
      author: 'Антон Лосенко',
      name: 'Владимир и Рогнеда',
      year: '1770',
      image: './src/img/historical/27.jpg',
    },
    {
      id: 28,
      author: 'Ян Матейко',
      name: 'Рейтан. Упадок Польши',
      year: '1866',
      image: './src/img/historical/28.jpg',
    },
    {
      id: 29,
      author: 'Шарль Лебрён',
      name: 'Вход Александра в Вавилон',
      year: '1665',
      image: './src/img/historical/29.jpg',
    },
    {
      id: 30,
      author: 'Василий Перов',
      name: 'Плач Ярославны',
      year: '1881',
      image: './src/img/historical/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Эдгар Дега',
      name: 'Голубые танцовщицы',
      year: '1897',
      image: './src/img/impressionism/1.jpg',
    },
    {
      id: 2,
      author: 'Пьер Огюст Ренуар',
      name: 'Большие купальщицы',
      year: '1887',
      image: './src/img/impressionism/2.jpg',
    },
    {
      id: 3,
      author: 'Эдуард Мане',
      name: 'Ланч на траве',
      year: '1863',
      image: './src/img/impressionism/3.jpg',
    },
    {
      id: 4,
      author: 'Станислав Юлианович Жуковский',
      name: 'Былое. Комната старого дома ',
      year: '1912',
      image: './src/img/impressionism/4.jpg',
    },
    {
      id: 5,
      author: 'Абрам Архипов',
      name: 'Баба в красном',
      year: '1910',
      image: './src/img/impressionism/5.jpg',
    },
    {
      id: 6,
      author: 'Клод Моне',
      name: 'Пруд с кувшинками',
      year: '1899',
      image: './src/img/impressionism/6.jpg',
    },
    {
      id: 7,
      author: 'Николай Мещерин',
      name: 'РЖАНЫЕ ПОЛЯ. ВИД ОТ ВОРОТ УСАДЬБЫ ДУГИНО В СТОРОНУ СЕЛА КОЛЫЧЕВО',
      year: '1906',
      image: './src/img/impressionism/7.jpg',
    },
    {
      id: 8,
      author: 'Валентин Серов',
      name: 'Открытое окно. Сирень',
      year: '1886',
      image: './src/img/impressionism/8.jpg',
    },
    {
      id: 9,
      author: 'Алексей Саврасов',
      name: 'Перед грозой',
      year: '1890',
      image: './src/img/impressionism/9.jpg',
    },
    {
      id: 10,
      author: 'Винсент Ван Гог.',
      name: ' Звёздная ночь',
      year: '1889',
      image: './src/img/impressionism/10.jpg',
    },
    {
      id: 11,
      author: 'Жорж Сёра',
      name: 'Воскресный день на острове Гранд-Жатт',
      year: '1884',
      image: './src/img/impressionism/11.jpg',
    },
    {
      id: 12,
      author: 'Джон Сингер Сарджент',
      name: 'Сладкое безделье',
      year: '1907',
      image: './src/img/impressionism/12.jpg',
    },
    {
      id: 13,
      author: 'Уолтер Сикерт',
      name: 'Крошка Дот Хетерингтон в Старом Бедфорде',
      year: '1889',
      image: './src/img/impressionism/13.png',
    },
    {
      id: 14,
      author: 'Камиль Писсарро',
      name: 'Бульвар Монмартр в Париже',
      year: '1897',
      image: './src/img/impressionism/14.jpg',
    },
    {
      id: 15,
      author: 'Максимильен Люс',
      name: 'Монмартр, улица Кортот, вид из Сен-Дени',
      year: '1900',
      image: './src/img/impressionism/15.jpg',
    },
    {
      id: 16,
      author: 'Анри де Тулуз-Лотрек',
      name: 'Марселла Лендер, танцующая болеро в кабаре',
      year: '1895',
      image: './src/img/impressionism/16.jpg',
    },
    {
      id: 17,
      author: 'Берта Моризо',
      name: 'Летний день',
      year: '1879',
      image: './src/img/impressionism/17.jpg',
    },
    {
      id: 18,
      author: 'Анри Руссо',
      name: 'Заклинательница змей',
      year: '1907',
      image: './src/img/impressionism/18.jpg',
    },
    {
      id: 19,
      author: 'Альфред Сислей',
      name: 'Мост Море́ летом',
      year: '1888',
      image: './src/img/impressionism/19.jpg',
    },
    {
      id: 20,
      author: 'Поль Сезанн',
      name: 'Натюрморт с драпировкой',
      year: '1895',
      image: './src/img/impressionism/20.jpg',
    },
    {
      id: 21,
      author: 'Жан Фредерик Базиль',
      name: 'В кругу семьи',
      year: '1867',
      image: './src/img/impressionism/21.jpg',
    },
    {
      id: 22,
      author: 'Матисс, Анри',
      name: 'Танец',
      year: '1910',
      image: './src/img/impressionism/22.jpg',
    },
    {
      id: 23,
      author: 'Поль Синьяк',
      name: 'Сосна Берто. Сен-Тропе',
      year: '1909',
      image: './src/img/impressionism/23.jpg',
    },
    {
      id: 24,
      author: 'Константин Коровин',
      name: 'В лодке',
      year: '1888',
      image: './src/img/impressionism/24.jpg',
    },
    {
      id: 25,
      author: 'Поль Гоген',
      name: 'Кафе в Арле',
      year: '1888',
      image: './src/img/impressionism/25.jpg',
    },
    {
      id: 26,
      author: 'Исаак Левитан',
      name: 'Мостик. Саввинская слобода',
      year: '1884',
      image: './src/img/impressionism/26.jpg',
    },
    {
      id: 27,
      author: 'Поль Серюзье',
      name: 'Ливень',
      year: '1893',
      image: './src/img/impressionism/27.jpg',
    },
    {
      id: 28,
      author: 'Пьер Боннар',
      name: 'Виноград',
      year: '1923',
      image: './src/img/impressionism/28.jpg',
    },
    {
      id: 29,
      author: 'Морис Дени',
      name: 'Завтрак',
      year: '1901',
      image: './src/img/impressionism/29.jpg',
    },
    {
      id: 30,
      author: 'Гюстав Кайботт',
      name: 'Крыши под снегом',
      year: '1878',
      image: './src/img/impressionism/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Василий Поленов',
      name: 'Московский дворик',
      year: '1877',
      image: './src/img/landscapes/1.jpg',
    },
    {
      id: 2,
      author: 'Фёдор Васильев',
      name: 'Мокрый луг',
      year: '1872',
      image: './src/img/landscapes/2.jpg',
    },
    {
      id: 3,
      author: 'Клод Лоррен',
      name: 'Отплытие святой Урсулы',
      year: '1614',
      image: './src/img/landscapes/3.jpg',
    },
    {
      id: 4,
      author: 'Архип Куинджи',
      name: 'Берёзовая роща',
      year: '1879',
      image: './src/img/landscapes/4.jpg',
    },
    {
      id: 5,
      author: 'Эль Греко',
      name: 'Вид Толедо',
      year: '1600',
      image: './src/img/landscapes/5.jpg',
    },
    {
      id: 6,
      author: 'Джорджоне',
      name: 'Буря',
      year: '1508',
      image: './src/img/landscapes/6.jpg',
    },
    {
      id: 7,
      author: 'Веласкес',
      name: 'Вилла Медичи в Риме. Полдень',
      year: '1630',
      image: './src/img/landscapes/7.jpg',
    },
    {
      id: 8,
      author: 'Иван Шишкин',
      name: 'Утро в сосновом лесу',
      year: '1889',
      image: './src/img/landscapes/8.jpg',
    },
    {
      id: 9,
      author: 'Алексей Саврасов',
      name: 'Грачи прилетели',
      year: '1871',
      image: './src/img/landscapes/9.jpg',
    },
    {
      id: 10,
      author: 'Ян Вермеер',
      name: 'Улочка',
      year: '1658',
      image: './src/img/landscapes/10.jpg',
    },
    {
      id: 11,
      author: 'Исаак Левитан',
      name: 'Над вечным покоем',
      year: '1894',
      image: './src/img/landscapes/11.jpg',
    },
    {
      id: 12,
      author: 'Алексей Венецианов',
      name: 'На пашне. Весна',
      year: '1820',
      image: './src/img/landscapes/12.jpg',
    },
    {
      id: 13,
      author: 'Александр Иванов',
      name: 'Ветка',
      year: '1850',
      image: './src/img/landscapes/13.jpg',
    },
    {
      id: 14,
      author: 'Илья Репин',
      name: 'Летний пейзаж',
      year: '1879',
      image: './src/img/landscapes/14.jpg',
    },
    {
      id: 15,
      author: 'Клод Жозеф Верне',
      name: 'Морской порт при лунном свете',
      year: '1771',
      image: './src/img/landscapes/15.jpg',
    },
    {
      id: 16,
      author: 'Жан-Оноре Фрагонар',
      name: 'Водопой',
      year: '1765',
      image: './src/img/landscapes/16.jpg',
    },
    {
      id: 17,
      author: 'Каналетто',
      name: 'Вестминстерский мост в Лондоне',
      year: '1746',
      image: './src/img/landscapes/17.jpg',
    },
    {
      id: 18,
      author: 'Пьер Огюст Ренуар',
      name: 'Мост в Шату',
      year: '1875',
      image: './src/img/landscapes/18.jpg',
    },
    {
      id: 19,
      author: 'Франсуа Буше',
      name: 'Пейзаж в окрестностях Бове',
      year: '1740',
      image: './src/img/landscapes/19.jpg',
    },
    {
      id: 20,
      author: 'Константин Маковский',
      name: 'Перемещение ковра Мухаммеда из Мекки в Каир',
      year: '1875',
      image: './src/img/landscapes/20.jpg',
    },
    {
      id: 21,
      author: 'Питер Брейгель',
      name: 'Охотники на снегу',
      year: '1565',
      image: './src/img/landscapes/21.jpg',
    },
    {
      id: 22,
      author: 'Поль Сезанн',
      name: 'Гора св. Виктории со стороны окрестностей Гарданны',
      year: '1890',
      image: './src/img/landscapes/22.jpg',
    },
    {
      id: 23,
      author: 'Джон Констебл',
      name: 'Вид на собор в Солсбери из епископского сада',
      year: '1823',
      image: './src/img/landscapes/23.jpg',
    },
    {
      id: 24,
      author: 'Винсент Ван Гог',
      name: 'Звёздная ночь',
      year: '1889',
      image: './src/img/landscapes/24.jpg',
    },
    {
      id: 25,
      author: 'Жорж-Пьер Сёра',
      name: 'Дробильщик камня',
      year: '1882',
      image: './src/img/landscapes/25.jpg',
    },
    {
      id: 26,
      author: 'Жюль Дюпре',
      name: 'Старый дуб',
      year: '1870',
      image: './src/img/landscapes/26.jpg',
    },
    {
      id: 27,
      author: 'Марианна Верёвкина',
      name: 'Муравейник',
      year: '1916',
      image: './src/img/landscapes/27.jpg',
    },
    {
      id: 28,
      author: 'Николай Рерих',
      name: 'Горная обитель',
      year: '1933',
      image: './src/img/landscapes/28.jpg',
    },
    {
      id: 29,
      author: 'Клод Моне',
      name: 'Мост Ватерлоо, туман',
      year: '1903',
      image: './src/img/landscapes/29.jpg',
    },
    {
      id: 30,
      author: 'Иван Айвазовский',
      name: 'Буря на море',
      year: '1873',
      image: './src/img/landscapes/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Тициан',
      name: 'Даная',
      year: '1560',
      image: './src/img/mythology/1.jpg',
    },
    {
      id: 2,
      author: 'Питер Пауль Рубенс',
      name: 'Союз Земли и Воды',
      year: '1618',
      image: './src/img/mythology/2.jpg',
    },
    {
      id: 3,
      author: 'Караваджо',
      name: 'Больной вакх',
      year: '1593',
      image: './src/img/mythology/3.jpg',
    },
    {
      id: 4,
      author: 'Виктор Васнецов',
      name: 'Иван-царевич на Сером Волке',
      year: '1888',
      image: './src/img/mythology/4.jpg',
    },
    {
      id: 5,
      author: 'Жак Луи Давид',
      name: 'Любовь Париса и Елены',
      year: '1788',
      image: './src/img/mythology/4.jpg',
    },
    {
      id: 6,
      author: 'Никола Пуссен',
      name: 'Пейзаж с Орфеем и Эвридикой',
      year: '1650',
      image: './src/img/mythology/6.jpg',
    },
    {
      id: 7,
      author: 'Рембрандт',
      name: 'Похищение Европы',
      year: '1632',
      image: './src/img/mythology/7.jpg',
    },
    {
      id: 8,
      author: 'Корреджо',
      name: 'Даная',
      year: '1530',
      image: './src/img/mythology/8.jpg',
    },
    {
      id: 9,
      author: 'Иероним Босх',
      name: 'Сад земных наслаждений',
      year: '1510',
      image: './src/img/mythology/9.jpg',
    },
    {
      id: 10,
      author: 'Жан Огюст Энгр',
      name: 'Эдип и Сфинкс',
      year: '1827',
      image: './src/img/mythology/10.jpg',
    },
    {
      id: 11,
      author: 'Илья Репин',
      name: 'Садко',
      year: '1876',
      image: './src/img/mythology/11.jpg',
    },
    {
      id: 12,
      author: 'Франсуа Буше',
      name: 'Купание Дианы',
      year: '1742',
      image: './src/img/mythology/12.jpg',
    },
    {
      id: 13,
      author: 'Джорджоне да Кастельфранко',
      name: 'Спящая Венера',
      year: '1510',
      image: './src/img/mythology/13.jpg',
    },
    {
      id: 14,
      author: 'Диего Веласкес',
      name: 'Венера с зеркалом',
      year: '1651',
      image: './src/img/mythology/14.jpg',
    },
    {
      id: 15,
      author: 'Франсиско Гойя',
      name: 'Сатурн, пожирающий своего сына',
      year: '1823',
      image: './src/img/mythology/15.jpg',
    },
    {
      id: 16,
      author: 'Рафаэль',
      name: 'Триумф Галатеи',
      year: '1512',
      image: './src/img/mythology/16.jpg',
    },
    {
      id: 17,
      author: 'Джон Уильям Уотерхаус',
      name: 'Волшебница Шалот',
      year: '1888',
      image: './src/img/mythology/17.jpg',
    },
    {
      id: 18,
      author: 'Питер Брейгель-Старший',
      name: 'Падение Икара',
      year: '1560',
      image: './src/img/mythology/18.jpg',
    },
    {
      id: 19,
      author: 'Веронезе',
      name: 'Марс и Венера',
      year: '1560',
      image: './src/img/mythology/19.jpg',
    },
    {
      id: 20,
      author: 'Жак-Луи Давид',
      name: 'Клятва Горациев',
      year: '1784',
      image: './src/img/mythology/20.jpg',
    },
    {
      id: 21,
      author: 'Николя Пуссен',
      name: 'Танец под Музыку Времени',
      year: '1636',
      image: './src/img/mythology/21.jpg',
    },
    {
      id: 22,
      author: 'Вильям-Адольф Бугро',
      name: 'Нимфы и Сатир',
      year: '1873',
      image: './src/img/mythology/22.jpg',
    },
    {
      id: 23,
      author: 'Антонио дель Поллайоло',
      name: 'Геракл и Гидра',
      year: '1475',
      image: './src/img/mythology/23.jpg',
    },
    {
      id: 24,
      author: 'Доссо Досси',
      name: 'Геркулес и Омфала',
      year: '1535',
      image: './src/img/mythology/24.jpg',
    },
    {
      id: 25,
      author: 'Сальватор Роза',
      name: 'Речной пейзаж с Аполлоном и Кумской сивиллой',
      year: '1665',
      image: './src/img/mythology/25.jpg',
    },
    {
      id: 26,
      author: 'Сандро Боттичелли',
      name: 'Весна',
      year: '1482',
      image: './src/img/mythology/26.jpg',
    },
    {
      id: 27,
      author: 'Адольф Вильям Бугро',
      name: 'Девушка и Амур',
      year: '1880',
      image: './src/img/mythology/27.jpg',
    },
    {
      id: 28,
      author: 'Луи Лагрене',
      name: 'Марс и Венера',
      year: '1770',
      image: './src/img/mythology/28.jpg',
    },
    {
      id: 29,
      author: 'Анн-Луи Жироде-Триозон',
      name: 'Сон Эндимиона',
      year: '1791',
      image: './src/img/mythology/29.jpg',
    },
    {
      id: 30,
      author: 'Уильям Блейк ',
      name: 'Геката',
      year: '1795',
      image: './src/img/mythology/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Питер Пауль Рубенс',
      name: 'Четыре части света',
      year: '1615',
      image: './src/img/epochs/1.jpg',
    },
    {
      id: 2,
      author: 'Антонис ван Дейк',
      name: 'Семейный портрет',
      year: '1621',
      image: './src/img/epochs/2.jpg',
    },
    {
      id: 3,
      author: 'Караваджо',
      name: 'Лютнист',
      year: '1595',
      image: './src/img/epochs/3.jpg',
    },
    {
      id: 4,
      author: 'Никола Пуссен',
      name: 'Танец под музыку времени',
      year: '1636',
      image: './src/img/epochs/4.jpg',
    },
    {
      id: 5,
      author: 'Рембрандт',
      name: 'Ночной дозор',
      year: '1642',
      image: './src/img/epochs/5.jpg',
    },
    {
      id: 6,
      author: 'Ян Вермеер',
      name: 'Девушка с жемчужной серёжкой',
      year: '1665',
      image: './src/img/epochs/6.jpg',
    },
    {
      id: 7,
      author: 'Франс Халс',
      name: 'Встреча офицеров и сержантов Каливерменской гражданской гвардии (членов стрелкового ополчения Св. Адриана)',
      year: '1633',
      image: './src/img/epochs/7.jpg',
    },
    {
      id: 8,
      author: 'Франс Снейдерс',
      name: 'Натюрморт с ведёрком для охлаждения вина',
      year: '1620',
      image: './src/img/epochs/8.jpg',
    },
    {
      id: 9,
      author: 'Якоб Йорданс',
      name: 'Бобовый король',
      year: '1640',
      image: './src/img/epochs/9.jpg',
    },
    {
      id: 10,
      author: 'Диего Веласкес',
      name: 'Менины',
      year: '1656',
      image: './src/img/epochs/10.jpg',
    },
    {
      id: 11,
      author: 'Жан-Оноре Фрагонар',
      name: 'Счастливые возможности качелей',
      year: '1768',
      image: './src/img/epochs/11.jpg',
    },
    {
      id: 12,
      author: 'Антуан Ватто',
      name: 'Отплытие с Киферы',
      year: '1717',
      image: './src/img/epochs/12.jpg',
    },
    {
      id: 13,
      author: 'Франсуа Буше',
      name: 'Завтрак',
      year: '1739',
      image: './src/img/epochs/13.jpg',
    },
    {
      id: 14,
      author: 'Джованни Баттиста Тьеполо',
      name: 'Аллегория планет и континентов',
      year: '1752',
      image: './src/img/epochs/14.jpg',
    },
    {
      id: 15,
      author: 'Каналетто',
      name: 'Возвращение Бучинторо к молу у Дворца дожей',
      year: '1730',
      image: './src/img/epochs/15.jpg',
    },
    {
      id: 16,
      author: 'Антон Лосенко',
      name: 'Прощание Гектора с Андромахой',
      year: '1773',
      image: './src/img/epochs/16.jpg',
    },
    {
      id: 17,
      author: 'Фёдор Рокотов',
      name: 'Коронационный портрет Екатерины II',
      year: '1763',
      image: './src/img/epochs/17.jpg',
    },
    {
      id: 18,
      author: 'Тициан',
      name: 'Венера Урбинская',
      year: '1538',
      image: './src/img/epochs/18.jpg',
    },
    {
      id: 19,
      author: 'Орацио Джентилески',
      name: 'Даная',
      year: '1621',
      image: './src/img/epochs/19.jpg',
    },
    {
      id: 20,
      author: 'Уильям Хогарт',
      name: 'Брачный контракт',
      year: '1745',
      image: './src/img/epochs/20.jpg',
    },
    {
      id: 21,
      author: 'Томас Гейнсборо',
      name: 'Мистер и миссис Эндрюс',
      year: '1750',
      image: './src/img/epochs/21.jpg',
    },
    {
      id: 22,
      author: 'Джошуа Рейнольдс',
      name: 'Младенец Геракл, удушающий змей, подосланных Герой',
      year: '1786',
      image: './src/img/epochs/23.jpg',
    },
    {
      id: 23,
      author: 'Адриан ван Остаде',
      name: 'Крестьяне за выпивкой',
      year: '1676',
      image: './src/img/epochs/22.jpg',
    },
    {
      id: 24,
      author: 'Геррит ван Хонтхорст',
      name: 'Пьяный скрипач',
      year: '1623',
      image: './src/img/epochs/24.jpg',
    },
    {
      id: 25,
      author: 'Михил Миревелт',
      name: 'Урок анатомии',
      year: '1617',
      image: './src/img/epochs/25.jpg',
    },
    {
      id: 26,
      author: 'Эль Греко',
      name: 'Вид Толедо',
      year: '1600',
      image: './src/img/epochs/26.jpg',
    },
    {
      id: 27,
      author: 'Жак Луи Давид',
      name: 'Клятва Горациев',
      year: '1784',
      image: './src/img/epochs/27.jpg',
    },
    {
      id: 28,
      author: 'Владимир Боровиковский',
      name: 'Екатерина II на прогулке в Царскосельском парке',
      year: '1794',
      image: './src/img/epochs/28.jpg',
    },
    {
      id: 29,
      author: 'Питер де Хох',
      name: 'Женщина с ребёнком у кладовки',
      year: '1658',
      image: './src/img/epochs/29.jpg',
    },
    {
      id: 30,
      author: 'Герард Терборх',
      name: 'Бокал лимонада',
      year: '1664',
      image: './src/img/epochs/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Пьетро Перуджино',
      name: 'Пьета',
      year: '1495',
      image: './src/img/renaissance/1.jpg',
    },
    {
      id: 2,
      author: 'Джентиле Беллини',
      name: 'Портрет дожа Джованни Мочениго',
      year: '1479',
      image: './src/img/renaissance/2.jpg',
    },
    {
      id: 3,
      author: 'Питер Брейгель',
      name: 'Вавилонская башня',
      year: '1563',
      image: './src/img/renaissance/3.jpg',
    },
    {
      id: 4,
      author: 'Рафаэль',
      name: 'Сикстинская Мадонна',
      year: '1520',
      image: './src/img/renaissance/4.jpg',
    },
    {
      id: 5,
      author: 'Веронезе',
      name: 'Пир в доме Левия',
      year: '1563',
      image: './src/img/renaissance/5.jpg',
    },
    {
      id: 6,
      author: 'Микеланджело',
      name: 'Сотворение Адама',
      year: '1511',
      image: './src/img/renaissance/6.jpg',
    },
    {
      id: 7,
      author: 'Ганс Гольбейн Младший',
      name: 'Послы',
      year: '1533',
      image: './src/img/renaissance/7.jpg',
    },
    {
      id: 8,
      author: 'Ян ван Эйк',
      name: 'Портрет четы Арнольфини',
      year: '1434',
      image: './src/img/renaissance/8.jpg',
    },
    {
      id: 9,
      author: 'Рогир Ван дер Вейден',
      name: 'Снятие с креста',
      year: '1440',
      image: './src/img/renaissance/9.jpg',
    },
    {
      id: 10,
      author: 'Исаак Оливер',
      name: 'Елизавета I и три богини (Юнона, Минерва и Венера)',
      year: '1558',
      image: './src/img/renaissance/9.jpg',
    },
    {
      id: 11,
      author: 'Жан Фуке',
      name: 'Дева Мария',
      year: '1450',
      image: './src/img/renaissance/11.jpg',
    },
    {
      id: 12,
      author: 'Леонардо да Винчи',
      name: 'Тайная вечеря',
      year: '1498',
      image: './src/img/renaissance/12.jpg',
    },
    {
      id: 13,
      author: 'Вольф Губер',
      name: 'Оплакивание Христа',
      year: '1524',
      image: './src/img/renaissance/13.jpg',
    },
    {
      id: 14,
      author: 'Сандро Боттичелли',
      name: 'Рождение Венеры',
      year: '1486',
      image: './src/img/renaissance/14.jpg',
    },
    {
      id: 15,
      author: 'Альбрехт Дюрер',
      name: 'Адам и Ева',
      year: '1507',
      image: './src/img/renaissance/15.jpg',
    },
    {
      id: 16,
      author: 'Иероним Босх',
      name: 'Несение креста.',
      year: '1500',
      image: './src/img/renaissance/16.jpg',
    },
    {
      id: 17,
      author: 'Корреджо',
      name: 'Даная',
      year: '1530',
      image: './src/img/renaissance/17.jpg',
    },
    {
      id: 18,
      author: 'Ян Провост',
      name: 'Скупой и Смерть',
      year: '1521',
      image: './src/img/renaissance/18.jpg',
    },
    {
      id: 19,
      author: 'Франческо Баккьякка',
      name: 'Мадонна с младенцем',
      year: '1520',
      image: './src/img/renaissance/19.jpg',
    },
    {
      id: 20,
      author: 'Маттиас Грюневальд',
      name: 'Поругание Христа',
      year: '1503',
      image: './src/img/renaissance/20.jpg',
    },
    {
      id: 21,
      author: 'Тициан',
      name: 'Венера Урбинская',
      year: '1534',
      image: './src/img/renaissance/21.jpg',
    },
    {
      id: 22,
      author: 'Франсуа Клуэ',
      name: 'Туалет дамы',
      year: '1571',
      image: './src/img/renaissance/22.jpg',
    },
    {
      id: 23,
      author: 'Джотто',
      name: 'Поцелуй Иуды',
      year: '1306',
      image: './src/img/renaissance/23.jpg',
    },
    {
      id: 24,
      author: 'Лукас Кранах Старший',
      name: 'Венера и Амур',
      year: '1509',
      image: './src/img/renaissance/24.jpg',
    },
    {
      id: 25,
      author: 'Мазаччо',
      name: 'Святой Петр исцеляет своей тенью',
      year: '1427',
      image: './src/img/renaissance/25.jpg',
    },
    {
      id: 26,
      author: 'Ханс Мемлинг',
      name: 'Mадонна с Младенцем и ангелом',
      year: '1480',
      image: './src/img/renaissance/26.jpg',
    },
    {
      id: 27,
      author: 'Якопо Понтормо',
      name: 'Портрет алебардиста',
      year: '1530',
      image: './src/img/renaissance/27.jpg',
    },
    {
      id: 28,
      author: 'Андрей Рублев',
      name: 'Троица',
      year: '1411',
      image: './src/img/renaissance/28.jpg',
    },
    {
      id: 29,
      author: 'Аньоло Бронзино',
      name: 'Венера, купидон и сатир',
      year: '1555',
      image: './src/img/renaissance/29.jpg',
    },
    {
      id: 30,
      author: 'Андреа Мантенья',
      name: 'Святой Себастьян',
      year: '1480',
      image: './src/img/renaissance/30.jpg',
    },
  ],
  [
    {
      id: 1,
      author: 'Виктор Васнецов',
      name: 'Богатыри',
      year: '1898',
      image: './src/img/russianArtists/1.jpg',
    },
    {
      id: 2,
      author: 'Николай Богданов-Бельский',
      name: 'Устный счёт',
      year: '1895',
      image: './src/img/russianArtists/2.jpg',
    },
    {
      id: 3,
      author: 'Василий Перов',
      name: 'Тройка',
      year: '1866',
      image: './src/img/russianArtists/3.jpg',
    },
    {
      id: 4,
      author: 'Александр Маковский',
      name: 'Надоела',
      year: '1897',
      image: './src/img/russianArtists/4.jpg',
    },
    {
      id: 5,
      author: 'Алексей Антропов',
      name: 'Портрет Петра III',
      year: '1762',
      image: './src/img/russianArtists/5.jpg',
    },
    {
      id: 6,
      author: 'Федор Рокотов',
      name: 'Коронационный портрет Екатерины II',
      year: '1763',
      image: './src/img/russianArtists/6.jpg',
    },
    {
      id: 7,
      author: 'Василий Суриков',
      name: 'Утро стрелецкой казни',
      year: '1881',
      image: './src/img/russianArtists/7.jpg',
    },
    {
      id: 8,
      author: 'Орест Кипренский',
      name: 'Портрет А. С. Пушкина',
      year: '1827',
      image: './src/img/russianArtists/8.jpg',
    },
    {
      id: 9,
      author: 'Николай Рерих',
      name: 'Помни!',
      year: '1924',
      image: './src/img/russianArtists/9.jpg',
    },
    {
      id: 10,
      author: 'Иван Айвазовский',
      name: 'Волна',
      year: '1889',
      image: './src/img/russianArtists/10.jpg',
    },
    {
      id: 11,
      author: 'Исаак Левитан',
      name: 'Март',
      year: '1895',
      image: './src/img/russianArtists/11.jpg',
    },
    {
      id: 12,
      author: 'Казимир Малевич',
      name: 'Черный квадрат',
      year: '1915',
      image: './src/img/russianArtists/12.jpg',
    },
    {
      id: 13,
      author: 'Карл Брюллов',
      name: 'Последний день Помпеи',
      year: '1833',
      image: './src/img/russianArtists/13.jpg',
    },
    {
      id: 14,
      author: 'Илья Репин',
      name: 'Летний пейзаж',
      year: '1879',
      image: './src/img/russianArtists/14.jpg',
    },
    {
      id: 15,
      author: 'Михаил Нестеров',
      name: 'Видение отроку Варфоломею',
      year: '1890',
      image: './src/img/russianArtists/15.jpg',
    },
    {
      id: 16,
      author: 'Василий Верещагин',
      name: 'Апофеоз войны',
      year: '1817',
      image: './src/img/russianArtists/16.jpg',
    },
    {
      id: 17,
      author: 'Константин Маковский',
      name: 'Дети, бегущие от грозы',
      year: '1872',
      image: './src/img/russianArtists/17.jpg',
    },
    {
      id: 18,
      author: 'Илья Репин',
      name: 'Вечорници',
      year: '1881',
      image: './src/img/russianArtists/18.jpg',
    },
    {
      id: 19,
      author: 'Владимир Боровиковский',
      name: 'Портрет Лопухиной',
      year: '1797',
      image: './src/img/russianArtists/19.jpg',
    },
    {
      id: 20,
      author: 'Валентин Серов',
      name: 'Девочка с персиками',
      year: '1887',
      image: './src/img/russianArtists/20.jpg',
    },
    {
      id: 21,
      author: 'Зинаида Серебрякова',
      name: 'За завтраком',
      year: '1914',
      image: './src/img/russianArtists/21.jpg',
    },
    {
      id: 22,
      author: 'Николай Ге',
      name: 'Тайная вечеря',
      year: '1863',
      image: './src/img/russianArtists/22.jpg',
    },
    {
      id: 23,
      author: 'Фёдор Решетников',
      name: 'Опять двойка',
      year: '1952',
      image: './src/img/russianArtists/23.jpg',
    },
    {
      id: 24,
      author: 'Виктор Васнецов',
      name: 'Иван-царевич на Сером Волке',
      year: '1888',
      image: './src/img/russianArtists/24.jpg',
    },
    {
      id: 25,
      author: 'Иван Богданов',
      name: 'За расчётом',
      year: '1890',
      image: './src/img/russianArtists/25.jpg',
    },
    {
      id: 26,
      author: 'Василий Перов',
      name: 'Приезд гувернантки в купеческий дом',
      year: '1866',
      image: './src/img/russianArtists/26.jpg',
    },
    {
      id: 27,
      author: 'Павел Федотов',
      name: 'Сватовство майора',
      year: '1852',
      image: './src/img/russianArtists/27.jpg',
    },
    {
      id: 28,
      author: 'Михаил Врубель',
      name: 'Царевна-Лебедь',
      year: '1900',
      image: './src/img/russianArtists/28.jpg',
    },
    {
      id: 29,
      author: 'Василий Поленов',
      name: 'Бабушкин сад',
      year: '1878',
      image: './src/img/russianArtists/29.jpg',
    },
    {
      id: 30,
      author: 'Алексей Венецианов',
      name: 'На жатве. Лето',
      year: '1827',
      image: './src/img/russianArtists/30.jpg',
    }
  ],
];




export default imagesPortraints;