let imagesRenaissance = [
  {
    id: 1,
    author: 'Леонардо да Винчи',
    name: 'Святая Анна с Мадонной',
    year: '1510',
    image: './src/img/renaissance/1.jpg',
  },
  {
    id: 2,
    author: 'Рафаэль',
    name: 'Святой Георгий и дракон',
    year: '1506',
    image: './src/img/renaissance/2.jpg',
  },
  {
    id: 3,
    author: 'Питер Брейгель',
    name: 'Вавилонская башня',
    year: '1563',
    image: './src/img/renaissance/3.jpg',
  },
  {
    id: 4,
    author: 'Рафаэль',
    name: 'Сикстинская Мадонна',
    year: '1520',
    image: './src/img/renaissance/4.jpg',
  },
  {
    id: 5,
    author: 'Веронезе',
    name: 'Пир в доме Левия',
    year: '1563',
    image: './src/img/renaissance/5.jpg',
  },
  {
    id: 6,
    author: 'Микеланджело',
    name: 'Сотворение Адама',
    year: '1511',
    image: './src/img/renaissance/6.jpg',
  },
  {
    id: 7,
    author: 'Питер Брейгель',
    name: 'Избиение младенцев',
    year: '1567',
    image: './src/img/renaissance/7.jpg',
  },
  {
    id: 8,
    author: 'Ян ван Эйк',
    name: 'Портрет четы Арнольфини',
    year: '1434',
    image: './src/img/renaissance/8.jpg',
  },
  {
    id: 9,
    author: 'Питер Брейгель',
    name: 'Фламандские пословицы',
    year: '1559',
    image: './src/img/renaissance/9.jpg',
  },
  {
    id: 10,
    author: 'Рафаэль',
    name: 'Мадонна в кресле',
    year: '1514',
    image: './src/img/renaissance/9.jpg',
  },
  {
    id: 11,
    author: 'Леонардо да Винчи',
    name: 'Мадонна Литта',
    year: '1491',
    image: './src/img/renaissance/11.jpg',
  },
  {
    id: 12,
    author: 'Леонардо да Винчи',
    name: 'Тайная вечеря',
    year: '1498',
    image: './src/img/renaissance/12.jpg',
  },
  {
    id: 13,
    author: 'Альбрехт Дюрер',
    name: 'Праздник венков из роз',
    year: '1506',
    image: './src/img/renaissance/13.jpg',
  },
  {
    id: 14,
    author: 'Сандро Боттичелли',
    name: 'Рождение Венеры',
    year: '1486',
    image: './src/img/renaissance/14.jpg',
  },
  {
    id: 15,
    author: 'Альбрехт Дюрер',
    name: 'Адам и Ева',
    year: '1507',
    image: './src/img/renaissance/15.jpg',
  },
  {
    id: 16,
    author: 'Рафаэль',
    name: 'Мадонна с розой',
    year: '1518',
    image: './src/img/renaissance/16.jpg',
  },
  {
    id: 17,
    author: 'Корреджо',
    name: 'Даная',
    year: '1530',
    image: './src/img/renaissance/17.jpg',
  },
  {
    id: 18,
    author: 'Сандро Боттичелли',
    name: 'Весна',
    year: '1482',
    image: './src/img/renaissance/18.jpg',
  },
  {
    id: 19,
    author: 'Франческо Баккьякка',
    name: 'Мадонна с младенцем',
    year: '1520',
    image: './src/img/renaissance/19.jpg',
  },
  {
    id: 20,
    author: 'Питер Брейгель',
    name: 'Притча о слепых',
    year: '1568',
    image: './src/img/renaissance/20.jpg',
  },
  {
    id: 21,
    author: 'Тициан',
    name: 'Венера Урбинская',
    year: '1534',
    image: './src/img/renaissance/21.jpg',
  },
  {
    id: 22,
    author: 'Ян ван Эйк',
    name: 'Гентский Алтарь',
    year: '1432',
    image: './src/img/renaissance/22.jpg',
  },
  {
    id: 23,
    author: 'Джотто',
    name: 'Поцелуй Иуды',
    year: '1306',
    image: './src/img/renaissance/23.jpg',
  },
  {
    id: 24,
    author: 'Леонардо да Винчи',
    name: 'Мадонна в скалах',
    year: '1486',
    image: './src/img/renaissance/24.jpg',
  },
  {
    id: 25,
    author: 'Мазаччо',
    name: 'Святой Петр исцеляет своей тенью',
    year: '1427',
    image: './src/img/renaissance/25.jpg',
  },
  {
    id: 26,
    author: 'Леонардо да Винчи',
    name: 'Благовещение',
    year: '1475',
    image: './src/img/renaissance/26.jpg',
  },
  {
    id: 27,
    author: 'Тициан',
    name: 'Кающаяся Марина Магдалина',
    year: '1565',
    image: './src/img/renaissance/27.jpg',
  },
  {
    id: 28,
    author: 'Андрей Рублев',
    name: 'Троица',
    year: '1411',
    image: './src/img/renaissance/28.jpg',
  },
  {
    id: 29,
    author: 'Веронезе',
    name: 'Брак в Кане Галилейской',
    year: '1562',
    image: './src/img/renaissance/29.jpg',
  },
  {
    id: 30,
    author: 'Тициан',
    name: 'Вакханалия',
    year: '1526',
    image: './src/img/renaissance/30.jpg',
  },
];

export default imagesRenaissance;