let imagesrussianArtists =  [
  {
    id: 1,
    author: 'Виктор Васнецов',
    name: 'Богатыри',
    year: '1898',
    image: './src/img/russianArtists/1.jpg',
  },
  {
    id: 2,
    author: 'Николай Богданов-Бельский',
    name: 'Устный счёт',
    year: '1895',
    image: './src/img/russianArtists/2.jpg',
  },
  {
    id: 3,
    author: 'Василий Перов',
    name: 'Тройка',
    year: '1866',
    image: './src/img/russianArtists/3.jpg',
  },
  {
    id: 4,
    author: 'Александр Маковский',
    name: 'Надоела',
    year: '1897',
    image: './src/img/russianArtists/4.jpg',
  },
  {
    id: 5,
    author: 'Алексей Антропов',
    name: 'Портрет Петра III',
    year: '1762',
    image: './src/img/russianArtists/5.jpg',
  },
  {
    id: 6,
    author: 'Федор Рокотов',
    name: 'Коронационный портрет Екатерины II',
    year: '1763',
    image: './src/img/russianArtists/6.jpg',
  },
  {
    id: 7,
    author: 'Василий Суриков',
    name: 'Утро стрелецкой казни',
    year: '1881',
    image: './src/img/russianArtists/7.jpg',
  },
  {
    id: 8,
    author: 'Орест Кипренский',
    name: 'Портрет А. С. Пушкина',
    year: '1827',
    image: './src/img/russianArtists/8.jpg',
  },
  {
    id: 9,
    author: 'Николай Рерих',
    name: 'Помни!',
    year: '1924',
    image: './src/img/russianArtists/9.jpg',
  },
  {
    id: 10,
    author: 'Иван Айвазовский',
    name: 'Волна',
    year: '1889',
    image: './src/img/russianArtists/10.jpg',
  },
  {
    id: 11,
    author: 'Исаак Левитан',
    name: 'Март',
    year: '1895',
    image: './src/img/russianArtists/11.jpg',
  },
  {
    id: 12,
    author: 'Казимир Малевич',
    name: 'Черный квадрат',
    year: '1915',
    image: './src/img/russianArtists/12.jpg',
  },
  {
    id: 13,
    author: 'Карл Брюллов',
    name: 'Последний день Помпеи',
    year: '1833',
    image: './src/img/russianArtists/13.jpg',
  },
  {
    id: 14,
    author: 'Илья Репин',
    name: 'Летний пейзаж',
    year: '1879',
    image: './src/img/russianArtists/14.jpg',
  },
  {
    id: 15,
    author: 'Михаил Нестеров',
    name: 'Видение отроку Варфоломею',
    year: '1890',
    image: './src/img/russianArtists/15.jpg',
  },
  {
    id: 16,
    author: 'Василий Верещагин',
    name: 'Апофеоз войны',
    year: '1817',
    image: './src/img/russianArtists/16.jpg',
  },
  {
    id: 17,
    author: 'Константин Маковский',
    name: 'Дети, бегущие от грозы',
    year: '1872',
    image: './src/img/russianArtists/17.jpg',
  },
  {
    id: 18,
    author: 'Илья Репин',
    name: 'Вечорници',
    year: '1881',
    image: './src/img/russianArtists/18.jpg',
  },
  {
    id: 19,
    author: 'Владимир Боровиковский',
    name: 'Портрет Лопухиной',
    year: '1797',
    image: './src/img/russianArtists/19.jpg',
  },
  {
    id: 20,
    author: 'Валентин Серов',
    name: 'Девочка с персиками',
    year: '1887',
    image: './src/img/russianArtists/20.jpg',
  },
  {
    id: 21,
    author: 'Зинаида Серебрякова',
    name: 'За завтраком',
    year: '1914',
    image: './src/img/russianArtists/21.jpg',
  },
  {
    id: 22,
    author: '',
    name: '',
    year: '',
    image: './src/img/russianArtists/22.jpg',
  },
  {
    id: 23,
    author: 'Фёдор Решетников',
    name: 'Опять двойка',
    year: '1952',
    image: './src/img/russianArtists/23.jpg',
  },
  {
    id: 24,
    author: 'Виктор Васнецов',
    name: 'Иван-царевич на Сером Волке',
    year: '1888',
    image: './src/img/russianArtists/24.jpg',
  },
  {
    id: 25,
    author: 'Иван Богданов',
    name: 'За расчётом',
    year: '1890',
    image: './src/img/russianArtists/25.jpg',
  },
  {
    id: 26,
    author: 'Василий Перов',
    name: 'Приезд гувернантки в купеческий дом',
    year: '1866',
    image: './src/img/russianArtists/26.jpg',
  },
  {
    id: 27,
    author: 'Павел Федотов',
    name: 'Сватовство майора',
    year: '1852',
    image: './src/img/russianArtists/27.jpg',
  },
  {
    id: 28,
    author: 'Михаил Врубель',
    name: 'Царевна-Лебедь',
    year: '1900',
    image: './src/img/russianArtists/28.jpg',
  },
  {
    id: 29,
    author: 'Василий Поленов',
    name: 'Бабушкин сад',
    year: '1878',
    image: './src/img/russianArtists/29.jpg',
  },
  {
    id: 30,
    author: 'Алексей Венецианов',
    name: 'На жатве. Лето',
    year: '1827',
    image: './src/img/russianArtists/30.jpg',
  }
]

export default imagesrussianArtists;